### PR TITLE
Allow linking multiple object files built from Souffle generated code

### PR DESCRIPTION
**Pull request by ruricolist**
This addresses #2356 using the approach linked by @quentin in his comments there. I've taken the linked commit from his branch and adjusted it to apply to Souffle master, with some adjustments for generating multiple files.

Since the inability to link object files of Souffle programs is relevant to multiple projects using Souffle, I think it is desirable to address the problem directly in the short term.

### CODE REVIEW

**Comment by quentin** [comment]
Hi @ruricolist thanks for integrating this!
By any chance, could you add a dedicated test that demonstrates the integration of multiple souffle programs ?

**Comment by b-scholz** [comment]
Please can you resolve the conflicts? Quentin has recently restructured the driver so that Souffle works better as a library.

**Comment by ruricolist** [comment]
I've rebased and added two tests (one to show how linking is broken without namespaces, one to show that namespaces fix the problem).

What's being tested here doesn't fit any of the predefined CMake test patterns, so most of the actual test is in Python.

**Review by quentin — APPROVED** [review]
Looks good to me, thanks for this port of my original change.

**Comment by SamedBayer** [comment]
Hi, when using Souffle version 2.4, I encounter a problem that did not exist with version 2.2. The issue arises when I attempt to generate and link multiple Souffle files. It gives the same error with #2356. 

The specific process of generating *.cpp files I follow is:

    souffle -g A.cpp A.dl
    souffle -g B.cpp B.dl
    souffle -g C.cpp C.dl  

Where A.dl is included in both B.dl and C.dl. This procedure was functioning correctly in version 2.2, but it leads to errors in the most recent version.

I am looking for assistance on how to use namespaces in my Souffle programs to resolve this issue. Specifically, can you please provide an example of a solution that employs namespaces to fix this problem?

**Comment by quentin** [comment]
Hi,
Are you trying to produce a single souffle program with sources A, B, and C ?
Or are you trying to produce 2 souffle programs: (A + B) and (A + C) ?

In the first case, you need to create a top level datalog file that includes A, B and C, and pass only that top file to `souffle -g`.

In the second case, you need to generate code with different namespaces for B and C:
- `souffle -g B.cpp --NS B B.dl` will generate code under the `namespace B { ... }`
- `souffle -g C.cpp --NS C C.dl` will generate code under the `namespace C { ... }`
- there is no need to call `souffle` for A since it is already included by B and C.

**Comment by SamedBayer** [comment]
Hi again,

It was the second case and it worked with different namespaces. 
Thanks.

**Pull request merged**
