### PR TITLE
String to number & number to string conversions Fix #657

### LINKED ISSUE #657: Type Cast using the AS keyword
I am currently trying to cast strings representing numbers to number to be able to compare the natural (instead of lexicographical) ordering. While looking through the [parser file](https://github.com/souffle-lang/souffle/blob/master/src/parser.yy) I found the AS keyword described as type cast.

However as gets flagged as unexpected identifier where ever it is used. How can we cast strings comprised of digits to numbers?
```
.decl debug(n:number)
debug(n) :- string = "1", n = string as number.
```

### PR DESCRIPTION
**Pull request by b-scholz**
Converting numbers to strings with new functor **to_number(string)** and strings to numbers with new functor **to_string(number)**.

### CODE REVIEW

**Comment by b-scholz** [comment]
Fix #657

**Comment by souffle-lang** [comment]
[56% (+55.56%) vs master 0%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/67/)

**Comment by souffle-lang** [comment]
[56% (+55.65%) vs master 0%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/68/)

**Comment by souffle-lang** [comment]
[56% (+55.65%) vs master 0%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/69/)

**Pull request merged**
