### PR TITLE
Disable frequency counter in the interpreter

### PR DESCRIPTION
**Pull request by XiaowenHu96**
The frequency counter in the interpreter causes a lot of performance overhead under profiling mode.
This makes the profiler report, in particular, the execution time of the interpreter inaccurate.

This PR disables the frequency counter in the interpreter so that user can at least get accurate profiling for the execution time.
If the frequency counter is really needed, the user should go for synthesiser mode as the result should be the same.

Once the PR is merged I'll update the documentation accordingly.

### CODE REVIEW

**Comment by mmcgr** [comment]
Would the performance impact still be substantial if a flag was used to only enable frequency counts when desired? `if (Global::config()::has("profileFrequency") { ...`

Synthesised has a similar issue, so a more general approach would be nice to have.

**Comment by XiaowenHu96** [comment]
> Would the performance impact still be substantial if a flag was used to only enable frequency counts when desired? `if (Global::config()::has("profileFrequency") { ...`
> 
> Synthesised has a similar issue, so a more general approach would be nice to have.

Yes, use a flag to enable frequency counts can be a better and more general solution for both execution models.
We just need to mention that with the frequency counter enabled in the interpreter, the user cannot rely on the reported execution time.
From my experience, the synthesiser result does not seem to be affected by frequency counts as much as the interpreter is. In the interpreter, we are observing a ~10x slowdown in some extreme cases, which makes the profiling result completely unreliable.

**Comment by XiaowenHu96** [comment]
By inaccurate result, I did not mean that the execution time is simply amplified. The issue is some of the rules can be much slower while some others are not affected too much - which can confuse the users about which part of the program they should improve.

**Comment by XiaowenHu96** [comment]
I actually have some free time this week, so I can implement the new option. Will do another PR.

**Pull request closed without merging**
