### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by mmcgr**

### CODE REVIEW

**Comment by mmcgr** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
RAM infrastructure changes are missing.

**Comment by b-scholz** [comment]
Also please order the list in terms of importance. The most important contributions  are 
 - Xiaowen's interpreter
 - David's provenance extensions
 - New RAM semantics with all subsequent changes (transformers/optimizers etc)
 - and the remaining points in no particular order 
Many thanks.

**Comment by b-scholz** [comment]
jenko test please

**Comment by mmcgr** [comment]
Jenkins, test this please

**Pull request merged**
