### PR TITLE
Fixes in souffle compile script

### PR DESCRIPTION
**Pull request by icesparrow**

### CODE REVIEW

**Comment by yanniss** [comment]
I now get (for "souffle -c"):
souffle-compile error: installation error: souffle header files cannot be found
failed to compile C++ source ./fileQMFAsn

I suspect this is due to this commit? The setup is that I "sudo make install" souffle (to /usr/local/bin) and have no other link to the souffle header directory. But this didn't use to be a problem. Sorry if I'm barking up the wrong tree and thanks for all the efforts!

**Comment by icesparrow** [comment]
Thanks for reporting this issue. This is indeed the commit that may have cause the issue. I do not see any issue on my machine though. Could you please let us know where your /bin/sh points to? souffle-compile is now using it instead of bash.

**Comment by yanniss** [comment]
Both my /bin/sh and /usr/bin/sh are actually bash.

$ /bin/sh --version
GNU bash, version 4.3.42(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by icesparrow** [comment]
@yanniss thanks for reporting your shell details, although I was wrong to suspect that this has something to do with the shell. The issue relates to path resolution by souffle and will be fixed by pull request #108 which also addresses wave invocations.

@scyptnex I understand that you are referring to a shebang before the license notice? You are probably right, so I will put it below.

**Comment by scyptnex** [comment]
I meant the removal of the copyright line "Copyright (C) ... Oracle ..."

**Comment by icesparrow** [comment]
Ah, sure, I have not noticed. Will fix that too.

**Pull request merged**
