### PR TITLE
Fix stoi error when passing --jobs=auto in non-OpenMP code path

### LINKED ISSUE #2475: no conversion for stoi when parsing --jobs=auto (without OPENMP)
Found in version 2.4.1 (tag)
Build on Mac OS Apple Silicon according to [build for Mac](https://souffle-lang.github.io/build#mac-os-x-build), OPENMP not installed

run souffle with `--jobs=auto`

## Expected result
Runs with default number of cores

## Actual result
Fails with `atoi: no conversion`

## Cause
The code in MainDriver does correctly parse the case of `--jobs=auto`, however later uses call `stoi()` without considering the possibility of the argument not being an integer; and this leads to a crash when it's called as `stoi("auto")`.

PR to follow

### PR DESCRIPTION
**Pull request by strRM**
When passing `auto` to the jobs in non-OpenMP mode, the `"auto"` ends up as an argument to `std::stoi` in  a couple of places, causing the program to crash. We fix this by mapping `auto` to `1` when OpenMP is not available.

Fixes #2475

### CODE REVIEW

**Review by quentin — COMMENTED** [review]
The openmp counterpart has an explicit test for for number vs `auto` and throws a runtime error for other cases. Should we repurpose/reuse that code?

**Comment by strRM** [comment]
Yeah, let me rewrite this a little bit.

**Comment by strRM** [comment]
I don't like the 2 ifdefs. I suppose I could introduce a boolean variable `haveOpenMP` and then use that instead the ifdefs.

**Review by quentin — APPROVED** [review]

**Comment by strRM** [comment]
I assume you're aware of the failures due to running out of disk space?

**Pull request merged**
