### PR TITLE
Add scripts for fuzzing with AFL and Radamsa

### PR DESCRIPTION
**Pull request by langston-barrett**
These are fairly complementary - It's easy to add more steps to the Radamsa script (e.g. using `jq` to check that the profiler JSON emitted by `souffle` is valid) because Radamsa is black-box, whereas AFL is likely to get deeper/generate better test cases because it's grey-box.

### CODE REVIEW

**Comment by mmcgr** [comment]
ok to test

**Review by b-scholz — APPROVED** [review]
Can you write some documentation on the wiki page how to run the fuzzing scripts?

**Review by b-scholz — APPROVED** [review]

**Comment by b-scholz** [comment]
It would be great to write a few notes here:
https://github.com/souffle-lang/souffle/wiki/Testing,-Continuous-Integration,-and-Deployment

**Comment by langston-barrett** [comment]
@b-scholz Will do!

**Pull request merged**
