### PR TITLE
Add configure flags to disable libz compression and sqlite.

### PR DESCRIPTION
**Pull request by mmcgr**

### CODE REVIEW

**Comment by mmcgr** [comment]
More changes to remove the old sqlite writer from the compiled version are needed before this can be used.

**Comment by b-scholz** [comment]
I wanted to ask -- is the flag -d removed as well. This is a flag for the generated executable only. It does not make sense anymore with the new IO system.

**Comment by mmcgr** [comment]
I missed some problems with the generated executable, which is why I closed this pull request. The old sqlite code is still in place which causes problems when sqlite is disabled. I'll look into that more thoroughly, and look at the flags, before reopening the pull request.

**Comment by b-scholz** [comment]
We should simply remove the –d option from the generated executable and the old SQL code.
It is not a very clean solution.

**Pull request closed without merging**
