### PR TITLE
`symbol` overload for `min` & `max`

### PR DESCRIPTION
**Pull request by ohamel-softwaresecure**
Defined using lexicographic ordering. This PR does not include #1353.

### CODE REVIEW

**Comment by ohamel-softwaresecure** [comment]
Running `make check -j8` locally passes `test/ram_arithmetic_test`. Is it possible to obtain a copy of `tests/testsuite.log`?

**Comment by mmcgr** [comment]
```
MultiArg
	OK (1/1)	SymbolMin
		TEST FAILED @ line 689 : expected ramBitCast<RamFloat>(result) == static_cast<RamFloat>(-100) where
			ramBitCast<RamFloat>(result) evaluates to 100
			static_cast<RamFloat>(-100) evaluates to -100

	FAILED (0/1)	FloatMin
		TEST FAILED @ line 676 : expected ramBitCast<RamUnsigned>(result) == 0 where
			ramBitCast<RamUnsigned>(result) evaluates to 100
			0 evaluates to 0

	FAILED (0/1)	UnsignedMin
		TEST FAILED @ line 663 : expected result == 0 where
			result evaluates to 50
			0 evaluates to 0

	FAILED (0/1)	Min
		TEST FAILED @ line 650 : expected result == symTab.lookup("100") where
			result evaluates to 199
			symTab.lookup("100") evaluates to 200

	FAILED (0/1)	SymbolMax
	OK (1/1)	FloatMax
	OK (1/1)	UnsignedMax
	OK (1/1)	Max
```

On travis there's an after_failure script run after failures that attempts to give feedback. It's collapsed by default at the end of the output. The jenkins server also runs the script after failures, although that tends to be less readable.

**Comment by ohamel-softwaresecure** [comment]
I was inadvertently running `make check` on the wrong branch. Can repo, fixed.

**Comment by ohamel-softwaresecure** [comment]
@mmcgr MacOS's pkger seems to have stalled?

**Pull request merged**
