### PR TITLE
Parallelizing scans with outer-most range query

### PR DESCRIPTION
**Pull request by HerbertJordan**

### CODE REVIEW

**Comment by souffle-lang** [comment]
[65% (+0.04%) vs master 65%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/137/)

**Comment by souffle-lang** [comment]
[65% (+0.03%) vs master 65%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/138/)

**Comment by souffle-lang** [comment]
[65% (+0.04%) vs master 65%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/139/)

**Comment by mmcgr** [comment]
Jenkins, test this please.

**Comment by souffle-lang** [comment]
[65% (+0.04%) vs master 65%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/144/)

**Pull request merged**
