### PR TITLE
Purge intermediate relations, but not input/output

### PR DESCRIPTION
**Pull request by adamjseitz**
In #2066, a new option was added to the C++ interface to allow purging intermediate relations. However, the current implementation purges input and output relations, which makes it impractical to use with `performIO` disabled (since the output relations would be purged before there is an opportunity for user code to read the output relation). By excluding input and output relations from those that are purged, the C++ interface can be used with `pruneImdtRels` enabled but `performIO` disabled.

### CODE REVIEW

**Comment by aeflores** [comment]
@adamjseitz maybe we should add a test? I see there are some C++ tests in https://github.com/souffle-lang/souffle/tree/master/tests/interface

**Comment by b-scholz** [comment]
Can you run clang-format? I.e.,
```
diff --git a/src/synthesiser/Synthesiser.cpp b/src/synthesiser/Synthesiser.cpp
[11](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:12)
index 58b7ead..487f340 100644
[12](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:13)
--- a/src/synthesiser/Synthesiser.cpp
[13](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:14)
+++ b/src/synthesiser/Synthesiser.cpp
[14](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:15)
@@ -466,7 +466,8 @@void Synthesiser::emitCode(std::ostream& out, const Statement& stmt) {
[15](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:16)
[16](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:17)
            auto Relation = synthesiser.lookup(clear.getRelation());
[17](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:18)
            bool isIntermediate = !contains(synthesiser.loadRelations, Relation->getName()) &&
[18](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:19)
-                !contains(synthesiser.storeRelations, Relation->getName()) && !Relation->isTemp();
[19](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:20)
+                                  !contains(synthesiser.storeRelations, Relation->getName()) &&
[20](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:21)
+                                  !Relation->isTemp();
[21](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:22)
[22](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:23)
            if (isIntermediate) {
[23](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:24)
                out << "if (pruneImdtRels) ";
[24](https://github.com/souffle-lang/souffle/runs/6947156929?check_suite_focus=true#step:3:25)
```

**Comment by adamjseitz** [comment]
> @adamjseitz maybe we should add a test? I see there are some C++ tests in https://github.com/souffle-lang/souffle/tree/master/tests/interface

I modified the existing `insert_print` test to utilize `pruneImdtRels` to verify that it's working - it didn't seem worth adding a near-duplicate test.

> Can you run clang-format? I.e.,

Sorry! I think the formatting is fixed now.

**Review by b-scholz — APPROVED** [review]
Thanks for the refactoring!

**Pull request merged**
