### PR TITLE
Fixed bug in aggregate clause extraction.

### PR DESCRIPTION
**Pull request by TomasPuverle**
I started playing with Souffle two days ago and ran into an assertion failure.  I was able to isolate the test to a minimal example; it is now added as "aggregate5" as part of this PR.

The failed assertion was in 

```
NumericConstant::Type TypeAnalysis::getPolymorphicNumericConstantType(const NumericConstant* nc) const {
    assert(hasValidTypeInfo(nc) && "numeric constant type not set");
    return numericConstantType.at(nc);
}
```

After digging into it, it seem the clause extraction transformer was incorrectly assigning the free/new variable type to be "symbol", instead of "unsigned".  As such, during the initial Transformation process all the polymorphic numeric constants were getting collected into the `numericConstantType` map; however, after the transformation (during the semantic analysis transform), the wrong type meant the constant no longer showed up in the visitor in ```TypeAnalysis::analyseNumericConstants```, causing the assertion later.

Here's a fix for the issue; I've only played with Souffle for the past two days.  Given the size of the codebase (I've only been looking at it since this afternoon), it's possible this is not the best fix - feedback would be appreciated.

As an aside, the code quality is awesome!  It was a pleasure reading through it.

### CODE REVIEW

**Comment by TomasPuverle** [comment]
Great, the checks are failing.

1) I did run clang format but it seems that on my machine it formats it the way my file is formatted.  What version of clang-format is the jenkins job running?
2) My machine is a bit slow, so I submitted the PR once it got through about 450 tests.  Naturally, tests 505 and 506 (count.dl) failed on the exact assertion I added.

Regarding 2), I actually added it because I was worried about this precise issue.  I didn't see anywhere if the user-defined types were "replaced" somewhere earlier in the transformer stages.

Any suggestions on how to fix/extract the inferred types for the new aggregate clause heads?

**Comment by b-scholz** [comment]
On MAC OS X the following benchmarks failed:
```
505: count -j8                                       FAILED (evaluation.at:43)
506: count   -c -j8                                  FAILED (evaluation.at:43)
```

**Comment by b-scholz** [comment]
Same for the other failing OS.

**Comment by b-scholz** [comment]
For the style-checker, you can apply the following diff:
```
diff --git a/src/ast/transform/MaterializeAggregationQueries.cpp b/src/ast/transform/MaterializeAggregationQueries.cpp
index c353d66e1..cf476dc19 100644
--- a/src/ast/transform/MaterializeAggregationQueries.cpp
+++ b/src/ast/transform/MaterializeAggregationQueries.cpp
@@ -311,14 +311,11 @@ bool MaterializeAggregationQueriesTransformer::materializeAggregationQueries(
                 auto const curArgType = argTypes[cur];
                 auto const isOfKind = [&](TypeAttribute ta) { return analysis::isOfKind(curArgType, ta); };
 
-                auto const typeName =
-                        isOfKind(TypeAttribute::Signed)
-                                ? "number"
-                                : isOfKind(TypeAttribute::Unsigned)
-                                          ? "unsigned"
-                                          : isOfKind(TypeAttribute::Float)
-                                                    ? "float"
-                                                    : isOfKind(TypeAttribute::Symbol) ? "symbol" : nullptr;
+                auto const typeName = isOfKind(TypeAttribute::Signed)     ? "number"
+                                      : isOfKind(TypeAttribute::Unsigned) ? "unsigned"
+                                      : isOfKind(TypeAttribute::Float)    ? "float"
+                                      : isOfKind(TypeAttribute::Symbol)   ? "symbol"
+                                                                          : nullptr;
 
                 assert(typeName && "Unrecognised type while creating aggregate clause head");
                 aggRel->addAttribute(mk<Attribute>(toString(*cur), typeName));

```

**Comment by b-scholz** [comment]
You find the failing test-case here:
```
souffle/tests/evaluation/count
```

The test-case `count.dl` is
```
// Souffle - A Datalog Compiler
// Copyright (c) 2019, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Tests aggregates involving multiple relations of various types

.type R = [ x : number ]

.decl NumbersA(x : number)
.decl NumbersB(x : number)
.decl SymbolsA(x : symbol)
.decl SymbolsB(x : symbol)
.decl RecordsA(x : R)
.decl RecordsB(x : R)
.decl CountNumbers(x : number)
.decl CountSymbols(x : number)
.decl CountRecords(x : number)

NumbersA(1).
NumbersB(2).
SymbolsA("a").
SymbolsA("b").
SymbolsB("b").
SymbolsB("c").
RecordsA([1]).
RecordsA([2]).
RecordsA([3]).
RecordsB([2]).
RecordsB([3]).
RecordsB([4]).
RecordsB([5]).
RecordsB(nil).

CountNumbers(x) :- x = count : { NumbersA(y), NumbersB(y) } .
CountSymbols(x) :- x = count : { SymbolsA(y), SymbolsB(y) } .
CountRecords(x) :- x = count : { RecordsA(y), RecordsB(y) } .

.output CountNumbers
.output CountSymbols
.output CountRecords
```

**Comment by b-scholz** [comment]
The reason is that the following assertion is triggered:
```
souffle: ast/transform/MaterializeAggregationQueries.cpp:323: souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(souffle::ast::TranslationUnit&)::<lambda(const souffle::ast::Clause&)>::<lambda(const souffle::ast::Aggregator&)>: Assertion `typeName && "Unrecognised type while creating aggregate clause head"' failed.
```

**Comment by TomasPuverle** [comment]
Hey Bernhard,

Please see my original comments, too, but let me try and rephrase for clarity:

Unfortunately, I was a bit eager with the PR - on my slow machine, 450 tests had run successfully when I decided to submit the PR.  The GitHub PR checks started running and actually caught up with my machine and failed on tests 505/506, hitting the assertion you mentioned above in count.dl.

I understand why/where the assertion is happening - *I* added it to prevent this very scenario because I am still not completely familiar with the full flow of the compiler.  
Before my change, that code was only assigning the type of "number", and falling back on "symbol" otherwise - this is clearly wrong (AFAICS) and my test (aggregate5.dl) demonstrates the bug.  I tried covering the full gamut of "basic types" but expected that, in fact, I would have to handle the full set of types (including .type and UDTs).  Hence the reason why I added the assertion. With the PR, I was hoping to start a discussion on how to provide a complete fix - and hence my question from above:  Right now, the code seems to rely on specifying a string as as attribute for the type; I can't see a way to provide the correct full type to the new clause head.

Regarding the style checker - I read the developer docs on the site and it said to use clang-format with the provided .clang-format file, which is what I did, resulting in the "bad" formatting your style checker reported.  Hence my confusion - either your Stylecheck check uses a different .clang-format, or you're perhaps it's using a different version of clang-format than me.  I was trying to figure out which it is.

Hope that clarifies things,

Tom

**Comment by mmcgr** [comment]
> Regarding the style checker - I read the developer docs on the site and it said to use clang-format with the provided .clang-format file, which is what I did, resulting in the "bad" formatting your style checker reported. Hence my confusion - either your Stylecheck check uses a different .clang-format, or you're perhaps it's using a different version of clang-format than me. I was trying to figure out which it is.

clang-format has fixed some bugs in each iteration that can cause different formatting, and sometimes adds new formatting options that also affect the result. In our use it's fairly stable from version 7 on. Except now (using version 11.0.0-5build1) - this looks more like a bug in clang-format, though, or a peculiar design decision that I don't see in the docs.

I've adjusted the builds to use 10, instead. Hopefully the LTS version is more stable.

So, Jenkins, test this please.

**Comment by azreika** [comment]
Impressive PR! Thanks for the fix!!

The assertion fails because records (and ADTs) aren't handled by your code.

The constructor for `ast::Attribute` actually takes in a string representing the attribute name (doesn't matter what this is in this context), and an `ast::QualifiedName` which represents the type of the attribute (internally, a vector of strings uniquely identifying the type.

In this case, you can probably just take any type in the deduced type set, and set the attribute type to be that value.
Essentially,
```
assert(!curArgType.empty() && "unexpected empty typeset");
aggRel->addAttribute(mk<Attribute>(toString(*cur), curArgType.begin()->getName()));
``` 
This means you don't have to worry about the other kinds (ADTs and records), which could be a little more annoying.

**Comment by TomasPuverle** [comment]
Thank for the input.  I'll have a look and re-submit.

**Comment by b-scholz** [comment]
Thanks for the work! Great contribution!

**Review by b-scholz — APPROVED** [review]

**Comment by TomasPuverle** [comment]
Thank you for the help and feedback.

**Pull request merged**
