### PR TITLE
CI for MSVC interface tests 

### PR DESCRIPTION
**Pull request by brianfairservice**
I have added a job which builds souffle in WSL, and then compiles and runs the interface tests in Windows using MSVC.

- tests/interface.at conditionally runs the interface tests with MSVC if the environment variable `SOUFFLE_TESTS_MSVC_VARS` is set.  This variable ought to point to the vcvars batch script that you want to use to setup the MSVC environment.
- I fixed a bunch of warnings from MSVC when compiling with `/W4`; mostly conversion, variable shadowing, and unused argument warnings.
- I got rid of the the parameters to `SouffleProgram::dumpInputs` and `SouffleProgram::dumpOutputs`.  These arguments were never used in either `SouffleProgram` or any of its subclasses, and all of the callers always relied on the default values of the arguments.
- I fixed a couple of errors in MSVC, which were mostly caused by the usage of functions which are not declared in windows.  There were a few ambiguous namespace errors as well.
- The travis job runs the tests with increased verbosity, and also outputs the *.out, and *.err files generated by the test, as well as the output from MSVC.  This is unlike all of the other jobs, but I thought it might be useful to developers on this project, the majority of whom I'm guessing do not have a windows environment setup where they can easily reproduce a failure. 

The swig tests are failing on my branch.  As far as I can tell, I haven't touched anything which should cause them to fail.  When I run the tests locally (in the docker image the tests use), the output from the test says: `Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /souffle/tests/testsuite.dir/01/libSwigInterface.so`.  `./configure --enable-swig` seems to have no effect.  I made this pull request anyway so I could start getting feedback, and so hopefully someone could help me troubleshoot this problem.

### CODE REVIEW

**Comment by mmcgr** [comment]
The swig tests seem to be failing because of the changes to the interface blocking compilation of swig
> I got rid of the the parameters to SouffleProgram::dumpInputs and SouffleProgram::dumpOutputs. These arguments were never used in either SouffleProgram or any of its subclasses, and all of the callers always relied on the default values of the arguments.

The parameters to those methods aren't used by the souffle code, but may be used by others so we would prefer the parameters to remain, incidentally fixing the swig problem.

**Comment by mmcgr** [comment]
> The swig tests seem to be failing because of the changes to the interface blocking compilation of swig
> 
> > I got rid of the the parameters to SouffleProgram::dumpInputs and SouffleProgram::dumpOutputs. These arguments were never used in either SouffleProgram or any of its subclasses, and all of the callers always relied on the default values of the arguments.
> 
> The parameters to those methods aren't used by the souffle code, but may be used by others so we would prefer the parameters to remain, incidentally fixing the swig problem.

Looking at this some more, if anyone was trying to pass an output stream to the dumpOutputs definition produced by the souffle synthesiser in the last few years, they would have been disappointed. Given that no one has ever questioned that behaviour, removing the parameter may be appropriate so I'm okay with removing the output stream.

**Comment by brianfairservice** [comment]
I have removed the parameters of `dumpInputs` and `dumpOutputs` on `SwigInterface`, and now the swig tests are passing.

I notice that the job I added is failing in your CI, but [it passes in mine](https://travis-ci.com/github/brianfairservice/souffle/jobs/385953736).  I've seen the failure we are seeing in your CI before: it was caused by the repository's files having windows line endings.  That is the reason why I modified the `.gitattributes` file.  But I have no idea why it is showing up again now, and only in your CI.  Let me know if you have any ideas.

**Comment by b-scholz** [comment]
Thank you so much for your contribution. 

It seems that the windows building script fails under Travis. Can you have a look?

**Comment by b-scholz** [comment]
It seems that the bootstrap script cannot be found.

**Comment by mmcgr** [comment]
> It looks like I fixed it. For some reason travis wasn't respecting the `.gitattributes` file, and I had to add a configuration setting to the `.travis.yml` file to not get windows line endings.

Good job finding that. I've been trying to debug this and hadn't got past 'it works for me'.

**Review by mmcgr — APPROVED** [review]
Fixes #1373

**Pull request merged**
