### PR TITLE
Test custom getopt only when it is enabled.

### PR DESCRIPTION
**Pull request by remysucre**
The custom `getopt` is enabled only when `SOUFFLE_CUSTOM_GETOPTLONG` is set; that flag defaults to OFF, so the test for `getopt` would fail. That test should only run when `SOUFFLE_CUSTOM_GETOPTLONG` is ON.

### CODE REVIEW

**Comment by quentin** [comment]
Hi,
The test is designed to work even when Souffle is not built with the custom implementation.
If the test does not work properly, please let me know and I'll try to fix.

**Comment by remysucre** [comment]
I'm attaching the test log below. I ran the tests on an ubuntu:20.04 docker on Apple M1.
[LastTest.log](https://github.com/souffle-lang/souffle/files/8515563/LastTest.log)

**Comment by quentin** [comment]
The messages suggest there might be an issue with the comparison of `char` with `-1`. It must be related to APPLE ARM architecture. It is as if `char` is unsigned, that would explain why the error message displays `\FF` instead of `-1`.

```
GetOptLong
		TEST FAILED @ line 487 : expected c == -1 where
			c evaluates to \FF
			-1 evaluates to -1
```

**Comment by remysucre** [comment]
I see. There are other issues on ARM related to signed/unsigned integers, so I'm going to switch to x86 for now. Will move this to an issue.

**Pull request closed without merging**
