### PR TITLE
Fixes #541

### LINKED ISSUE #541: Refactoring of RAM
The RAM intermediate representation needs to be refactored. We should aim to apply the same design patterns as in AST, i.e., prototype pattern and subscriber mechanism for analyses, and transformers. In addition, the intermediate representation should be separated from the operations on it (e.g., levelling). We should have a transformer pipeline similar to the AST, i.e., RAM should mimic a similar design like the AST of Souffle.

 * Tidy-up class description and add prototype boilerplate code (done)

 * RamRelation needs to be split into a reference and a relation declaration, and remove RamCreate (done)

 * RamTranslationUnit is to be generated by the AST Translator (done)

 * Introduce RAM transformer for converting  simple RAM scans to indexed expressions (done)

 * Introduce RAM transformers for levelling (placing conditions at the most outer looper so that the semantic is not violated)  (done)
 
 * Introduce RAM analyses for indexing (done)

 * Introduce semantic checker for RAM as a RAM Transformer 

 * Adapting Interpreter and Synthesiser (done)

### PR DESCRIPTION
**Pull request by b-scholz**
Refactoring of RAM. See issue #541

### CODE REVIEW

**Comment by b-scholz** [comment]
jenkins test this

**Comment by b-scholz** [comment]
run tests

**Comment by mmcgr** [comment]
Jenkins runs the tests again every time a new commit is added to the PR, similar to travis. To make them run again manually, you just need to be more polite. Jenkins, test this please.

**Comment by b-scholz** [comment]
Nice - by the way - the packaging is failing. Do you have any insight why?

**Comment by mmcgr** [comment]
I think you just need to remove mention of RamSemanticChecker.h from Makefile.am

**Comment by b-scholz** [comment]
Great - thanks.

**Comment by b-scholz** [comment]
Martin - it works - gimme the green light :-)

**Pull request merged**
