### PR TITLE
Bit shift operators

### PR DESCRIPTION
**Pull request by ohamel-softwaresecure**
Adds `<<`, `>>`, and `>>>`, using the same semantics as Java ( https://docs.oracle.com/javase/specs/jls/se13/html/jls-15.html#jls-15.19 ). These operators are polymorphic for integral numeric types. `>>>` isn't technically needed but it saves the user from having to manually convert between signed/unsigned.

### CODE REVIEW

**Comment by mmcgr** [comment]
The tests seem to have problems when using 64bit RamDomains.
In case you haven't looked at that usage yet:
`./configure --enable-64bit-domain`

**Comment by ohamel-softwaresecure** [comment]
My guess is that the 64-bit domain test is failing on the sign-extended shift. I'll check that shortly. Is there a way to have different golden-test CSVs for 64-bit and 32-bit variants in the test suite?

**Comment by ohamel-softwaresecure** [comment]
Or just any shift really. Manual checks show they work correctly w/ 64 bit domains, but obviously that changes the semantics by allowing a larger range. I don't see any obvious way to have 64-bit specific tests; without that I can't add shift overflow cases to the test case. I'll change the test case to avoid those for now.

**Comment by mmcgr** [comment]
When parsing the input there is a macro `RAM_DOMAIN_SIZE` which will be either 32 or 64. That can be used to adjust the program so that the output is the same. Not quite what you're looking for but closer.

A low priority plan is to set up the autotest file with the configure script. That would allow test selection based on whether 64 bit domains were used. These tests will be revisited when that happens.

**Comment by ohamel-softwaresecure** [comment]
That's the solution I eventually went with in 35fa073. If it finds itself in 64 bit mode it applies some bit twiddling to pretend it's working with 32 bits.

**Pull request merged**
