### PR TITLE
Tuning CI multi-thread configuration

### PR DESCRIPTION
**Pull request by XiaowenHu96**
This is related to #1985

### CODE REVIEW

**Comment by quentin** [comment]
Might be necessary to fix `Engine.cpp` this way: https://github.com/souffle-lang/souffle/pull/1977/commits/69dfb9e79c1966520ff623c9bf581ad6c35a305d

**Comment by XiaowenHu96** [comment]
> Might be necessary to fix `Engine.cpp` this way: [69dfb9e](https://github.com/souffle-lang/souffle/commit/69dfb9e79c1966520ff623c9bf581ad6c35a305d)

whoops. Nice catch.

**Comment by b-scholz** [comment]
It is for me unclear whether the tests are executed in parallel or not. It seems the performance of the VMs are quite elastic.

**Comment by b-scholz** [comment]
Thanks for the contribution.

**Review by b-scholz — APPROVED** [review]

**Pull request merged**
