### PR TITLE
Renaming RAM Choice to IfExists

### PR DESCRIPTION
**Pull request by b-scholz**
This PR renames RAM's Choice to the more suitable name if-exists.

### CODE REVIEW

**Comment by b-scholz** [comment]
Jenkins test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Jenkins test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Jenkins test this please

**Comment by b-scholz** [comment]
Jenkins test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Review by XiaowenHu96 — APPROVED** [review]

**Comment by b-scholz** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Jenkins, test this please

**Pull request merged**
