### PR TITLE
Missing include file in CompiledSouffle.h

### PR DESCRIPTION
**Pull request by b-scholz**
C++ Interface breaks without the <fstream> include

### CODE REVIEW

**Comment by mmcgr** [comment]
What is it that breaks? I don't see anything in CompiledSouffle.h that needs fstream. Unless I missed something, is there a more local header/cpp file to put the fstream include in?

**Comment by mmcgr** [comment]
Separate to that, it seems that the style check is no longer checking the whole PR, just the last commit. The includes should be in lexicographical order - so fstream should be down a few lines.

**Comment by b-scholz** [comment]
Andres and I have been working on a new Python language interface using SWIG. SWIG permits also other languages (JAVA, CLISP, etc.). It seems that the generated C++ code of souffle requires fstream.h when compiled with the flag __EMBEDDED_SYSTEM__ due to the new I/O system. The other alternative is to produce a include directive in the output in souffle (which is less desirable).

**Comment by mmcgr** [comment]
The IO system already includes fstream, so that seems odd. If it's an include that is only needed when the EMBEDDED_FLAG is enabled, though, CompiledSouffle.h is a reasonable place for it.

**Comment by b-scholz** [comment]
Please don't merge - there is an issue. I need to update the include somewhere else.

**Pull request closed without merging**
