### PR TITLE
Generate unstable deb and rpm packages

### PR DESCRIPTION
**Pull request by mmcgr**
Generate unstable deb and rpm(fedora27/centos7) packages via docker images on travis
Add make install check to travis
Label travis jobs so you can tell what they are.

### CODE REVIEW

**Comment by souffle-lang** [comment]
[65% (+64.71%) vs master 0%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/74/)

**Comment by lyndonhenry** [comment]
Docker stuff looks like it will all work fine, and it's quite good enough for the moment. It's not exactly the way Docker is really "meant" (yes, I'm opinionated) to be used though, as instead of copying scripts into containers, the commands of those scripts should be in Dockerfiles, then the images prebuilt and uploaded somewhere (i.e. Dockerhub). Then in Travis, all we'd have to do is build a dependent image that within compiles Souffle. We could even push such built images back to Dockerhub, tagged with a commit. This is advantageous as it makes things significantly faster (we don't have to reinstall packages each Travis run), more maintainable (Dockerfiles are simple), more robust (we have precise guarantees over what worked for which version under exactly defined conditions), and more informative for the user (they can know exactly how Souffle must be built for their particular platform). Anyway, all of this is rather an involved project, so not a rebuttal to this current PR, but more a consideration for the future. It wouldn't be difficult, just time consuming, but depending on how much we moved to Docker, potentially quite beneficial.

**Comment by mmcgr** [comment]
The reason for not using pre-built docker files was to test that souffle could be built using the latest versions of the expected dependencies for that particular OS before making a package. If we set up the image beforehand we could miss changes in the dependencies until the image was updated. Which I did not document so at the very least I should add comments to that effect.

Using more precisely defined versions of the dependencies is far more robust, as you say, but is less helpful for ensuring the package works for new users.

**Comment by lyndonhenry** [comment]
Oh right, this makes much more sense -- instead of guaranteeing "souffle works under such and such conditions" we guarantee "using this bash script to build souffle on this platform worked at this time". I like it, it's nice and practical.

**Comment by souffle-lang** [comment]
[65% (+64.72%) vs master 0%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/76/)

**Comment by souffle-lang** [comment]
[65% (+64.67%) vs master 0%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/77/)

**Comment by souffle-lang** [comment]
[64% (+64.21%) vs master 0%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/79/)

**Comment by souffle-lang** [comment]
[64% (+0.02%) vs master 64%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/80/)

**Pull request merged**
