### PR TITLE
Add word size to help screen

### PR DESCRIPTION
**Pull request by mingodad**

### CODE REVIEW

**Comment by mingodad** [comment]
Would be nice to also add the version of the build like `souffle -h` does:
```
----------------------------------------------------------------------------
Version: 2.3-137-gf2f974194
Word size: 32 bits
----------------------------------------------------------------------------
```

**Comment by quentin** [comment]
Yes, would also be nice to know the status of enabled/disabled features like sqlite, openmp:
https://github.com/souffle-lang/souffle/blob/f2f974194a2744b38234b6bbc8cfdaf539af2809/CMakeLists.txt#L77-L87

They end-up as C macros (`target_compile_definitions` of `libsouffle`):
https://github.com/souffle-lang/souffle/blob/f2f974194a2744b38234b6bbc8cfdaf539af2809/src/CMakeLists.txt#L255-L305

**Comment by mingodad** [comment]
Hello @quentin I just added the version to the help string, and also added some of the compiled options enabled in the `souffle` help screen see here https://github.com/souffle-lang/souffle/pull/2353

**Review by b-scholz — APPROVED** [review]
Thanks for adding the feature!

**Pull request merged**
