### PR TITLE
Live profiler and Profile DB

### PR DESCRIPTION
**Pull request by mmcgr**
- Record profiling information in an hierarchical database.
- Atom frequency logging supports iterations better.
- Adds load/store timing to the profile logs
- Profiling logging output is more consistent and in a more easily parsed json format.
- A live mode is added, `souffle a.dl -l`, that runs the profiler in a separate thread during souffle execution.
- Fixes for bugs revealed by profiling changes
- Refactoring.

### CODE REVIEW

**Comment by souffle-lang** [comment]
[64% (+64.28%) vs master 0%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/73/)

**Comment by lyndonhenry** [comment]
Had a quick look at this, there's way too much to review properly, but it all seems to be pretty good (apart from the comment above on the possibly accidentally included file). Would probably be good to have another pair of eyes go over it as well, just because there's so much stuff going on.

**Comment by lyndonhenry** [comment]
Had a quick look at this, there's way too much to review properly, but it all seems to be pretty good (apart from the comment above on the possibly accidentally included file). Would probably be good to have another pair of eyes go over it as well, just because there's so much stuff going on.

**Comment by mmcgr** [comment]
Which accidentally included file was that? I think your comment on that was lost.

I see now that the empty .gitmodules was accidentally removed and souffle2lb.cpp was accidentally 'tidied', but the changes are reasonable, if unrelated to the point of this PR, and undoing the changes a little problematic.

**Comment by mmcgr** [comment]
Also, I think in future that if we have big changes like this we should use a branch, do small PRs to that branch, and then the final merge to master is of code that has already been reviewed. The wisdom of hindsight.

**Comment by lyndonhenry** [comment]
Oops, you are right, I forgot to submit my comment. It was that src/ProfileDatabase.cpp has a main method in it and looks like a demo included with src/ProfileDatabase.h.

Also agree with said branch-merge idea.

**Comment by souffle-lang** [comment]
[64% (+64.27%) vs master 0%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/75/)

**Comment by souffle-lang** [comment]
[64% (+64.21%) vs master 0%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/78/)

**Pull request merged**
