### PR TITLE
WIP: Support for Python bindings using pybind

### PR DESCRIPTION
**Pull request by TomasPuverle**
TODO before review:

Python code features:

- [x] Finish exposing all current existing interfaces
   - [ ] Symbol table.  Interface TBD.
   - [ ] Record table.  Interface TBD.
- [x] Handle aux/primary arity, provenance and whether or not it needs to be handled/exposed
- [ ] Handle records
- [ ] Synthesize named tuples for UDTs
- [ ] Support for writing functors in Python (see #1831)
- [ ] Support wrapping of Python objects in Souffle programs

Infra work Items:
- [ ] Make python support conditional
- [ ] Update infra containers to add poetry/nox
- [ ] Linting
- [ ] Mypy
- [ ] More complete nox runner
- [ ] Finish test coverage
- [ ] Documentation
- [ ] Doctests
- [ ] Update README to install poetry and nox
- [ ] Improve distcheck for Python code

### CODE REVIEW

**Comment by TomasPuverle** [comment]
For the Ubuntu LTS distcheck, it seems that `bootstrap` is not getting executed and so the git submodule is not getting pulled in.  Maintainers, would be you be able to address this, please?

**Comment by mmcgr** [comment]
> For the Ubuntu LTS distcheck, it seems that `bootstrap` is not getting executed and so the git submodule is not getting pulled in. Maintainers, would be you be able to address this, please?

distcheck copies the src directory, and various other files in the list of files to distribute, then builds from the copy to verify that they really are the list of files needed to build - this may be where things are going wrong. The bootstrap file doesn't exist at this point.

**Comment by TomasPuverle** [comment]
I see, thanks.  It would then need to be adjusted to copy the `extern` directory, which is where I introduced a 3rd-party github submodule.

I am open to providing the dependencies in a different way, however, at this point I think it would be more useful for me to get some feedback on the PR before changing the build system.

**Comment by TomasPuverle** [comment]
Hi @b-scholz, @mmcgr, @azreika,
 
Any feedback on this?  I can't tell if the lack of response is because there's no interest, because it's close to the holidays, because it's only a draft PR or perhaps because the build is failing distcheck? (Which isn't really my fault - and I can't do much about it).  I even tried asking on Zulip but haven't heard anything there either.

Thanks!

Tom

**Comment by b-scholz** [comment]
Sorry for the delayed feedback - I have been on holidays. At the moment we have the SWIG interface which provides a very rudimentary interface. There is a native interface for Haskell (by Luc), which of course is more sophisticated than the SWIG interface. 

This python interface should also aim to improve the Python experience so that it adds value.  Your list of extensions is great. For the interface, I would suggest that you also consider records and abstract-data types. 

There are mechanisms to expose these data-types in form of JSON. We use it for the I/O. 

In addition, we need to work harder to disentangle the Python interface from the synthesiser. We don't want dependencies for each new language interface.

Again, great work! Keep going!

**Comment by b-scholz** [comment]
As Martin has already mentioned, there are some include issues. We use automake that differentiates between build, install, and source directories. 
Something went wrong with your includes because of the `make distcheck`.
```
[01m[K../../../src/pybind/cpp/souffle_py.cpp:7:10:[m[K [01;31m[Kfatal error: [m[Kpybind11/pybind11.h: No such file or directory
    7 | #include [01;31m[K<pybind11/pybind11.h>[m[K
      |          [01;31m[K^~~~~~~~~~~~~~~~~~~~~[m[K
compilation terminated.
```

**Comment by TomasPuverle** [comment]
Hi Bernhard @b-scholz,

Thank you for the feedback and happy holidays!  I am happy you think this is worth pursuing - that's all I needed to know to continue.  I didn't want spend a lot of time on it and have it rejected because it may not be considered "suitable" in some way.

Quick responses to your observations/feedback:

1) I am aware of the Swig interface but its "lack of features" in Python is why I embarked on this project
2) Records and ADTs are already on the "planned" list :)
3) I agree about disentangling the code generation.  I've already been looking into integrating a template engine with a generic visitor framework (you'll see some of my other PRs/cleanups, too) but I didn't want to marry two such large changes.  For now, the Synthetizer changes are complete and straightforward to understand.  Hopefully you agree that tackling this problem in stages (and generalizing in the process) is the correct approach for your project.

As for the distcheck rule - yes, it needs to be adjusted; however, before doing that I was trying to ascertain that you and the other maintainers were ok with me using git submodules for dependencies and using `extern` as the destination directory for them.  Based on your message, I will assume your tacit agreement for now and I will fix distcheck accordingly.

Kind regards,

Tom

**Comment by TomasPuverle** [comment]
@b-scholz @mmcgr 

Would you be able to install `nox` on the build machines?  (It seems poetry is already installed, which is great)

`pip3 install --user --upgrade nox` as the build user, or just `pip3 install nox` if you're ok with installing globally.

Thanks!

**Comment by TomasPuverle** [comment]
Ping please! :wink:

**Comment by b-scholz** [comment]
I have installed "nox" on the machines. It could be that the docker images need to change as well for this.

**Comment by b-scholz** [comment]
Hey Jenkins, test this please x

**Comment by TomasPuverle** [comment]
Alas, Jenkins not happy.

**Comment by b-scholz** [comment]
We need to change the docker images in souffle/docker accordingly (i.e. we need to add the nox packages).

**Comment by TomasPuverle** [comment]
Hi Bernhard,

I had a quick look through the `Dockerfile`s in the souffle repo and I don't think I can make those changes.  Would you please be able to help when you have some time?  No rush, I can make progress elsewhere in the meantime.
Thank you,

Tom

**Comment by b-scholz** [comment]
In the meantime (unfortunately it will take some more time) could I ask you to make the build conditional (similar to SQLITE3)?
If the package does not exist, the python binding will not be enabled in the build.

**Comment by b-scholz** [comment]
Hey Jenkins, test this please x

**Comment by b-scholz** [comment]
Hey Jenkins, test this please

**Comment by TomasPuverle** [comment]
I was planning to do that.  Added to TODO list above.

**Comment by b-scholz** [comment]
Hey Jenkins, test this please

**Comment by TomasPuverle** [comment]
Hi @b-scholz,

It seems your fixes are now finding nox for "Ubuntu LTS distcheck" and "Ubuntu LTS - 64bit domains" - awesome!  Still failing in OSX and Ubuntu Dev but it seems your changes are working.
Thanks,

Tom

**Comment by b-scholz** [comment]
I am still learning docker on the fly - I forgot to issue "commit" after installing the new packages. 
Give me another 1-2 attempts to fix your problem.

**Comment by b-scholz** [comment]
I noticed that there are issues with the distcheck build:
```
...
make[4]: warning: -j4 forced in submake: resetting jobserver mode.
/usr/bin/nox -f ../../../noxfile.py --reuse-existing-virtualenvs -s tests -- --souffle-path=/souffle/souffle-2.0.2-898-g152e8037c/_build/sub/../../src/souffle
nox > Noxfile /souffle/souffle-2.0.2-898-g152e8037c/noxfile.py not found.
make[4]: *** [Makefile:705: check-local] Error 2
make[4]: Leaving directory '/souffle/souffle-2.0.2-898-g152e8037c/_build/sub/tests'
make[3]: *** [Makefile:572: check-am] Error 2
```

Most likely, this is related a misplaced source/build/install directory in the script for nox.

**Comment by b-scholz** [comment]
I still need to fix the Mac OS X box.

**Comment by b-scholz** [comment]
Perhaps we retire this WIP and revive it as soon as more human resources are available. I will link a new issue to this WIP.

**Pull request closed without merging**
