### PR TITLE
Fixed up tests in examples folder

### PR DESCRIPTION
**Pull request by azreika**
Unlike the other tests, the tests in the examples folder aren't regularly run with each change to Souffle. As a result, several tests no longer pass with the current version of Souffle. This PR ensures all tests pass, either by fixing the test or by fixing Souffle.

The tests fixed up are:
* `access-policy` and `magic-access-policy`
    * The SSN field in the fact files were of the form "XXX-XX-XXXX", but being read in as numbers by the Datalog. The type was fixed to string.
    * Because it was originally being read in as numbers, the old version of Souffle would have read the first three digits only. As a result, the output file only contained those 4 digits. The ouptut file was fixed to contain all SSN digits. The only difference between the original and current output file should be the SSN field.  
* `euclid`
    * Added missing warnings for unused variables
* `tic-tac-toe`
     * One relation has arity 20, which was not supported by the interpreter. Updated interpreter to handle relations of up to arity 20.
* `graph`
    * Lingering unnecessary type definition which broke the type checker
* `prime2` and `magic_prime2`
    * `range` is now a keyword in Souffle, and can't be used for relation names. Changed relation name to `candidate`
* `minpath3` and `nfsa2fsa`
    * Fixed incorrect type information 
* `strategies`, `comp-parametrized`, and `comp-parametrized-multilvl`
     * The delimiter for component relations is now `.`, rather than `-`. Updated output filenames to match

Resolves issue #1501.

### CODE REVIEW

**Comment by mmcgr** [comment]
"the old version of Souffle would have read the first three digits only. As a result, the output file only contained those 4 digits. " ...

**Comment by mmcgr** [comment]
I could add a test to jenkins for the Examples folder. We don't reeeally want to maintain them, but it would be good to know when they do start failing.

**Comment by azreika** [comment]
> "the old version of Souffle would have read the first three digits only. As a result, the output file only contained those 4 digits. " ...

hahahah woops pls forgive, I had to go through 201K lines of SSNs for this test 😩 (not manually, but like...)

**Comment by azreika** [comment]
> I could add a test to jenkins for the Examples folder. We don't reeeally want to maintain them, but it would be good to know when they do start failing.

I think it's important to keep them up to date at least every once in a while, so some test that runs occassionally on the master branch (instead of for every PR) might be good. They're nice tests to see how Souffle could be used in the real world. Personally, they're also nice complex tests that might pick up on things other tests won't sometimes for some big changes.

**Pull request merged**
