### PR TITLE
WIP Add support for recursive aggregate

### PR DESCRIPTION
**Pull request by remysucre**

### CODE REVIEW

**Comment by b-scholz** [comment]
I looked at the WIP again.  As discussed, we need a semantic check for recursive-aggregate relations. I would check the following:
 
- [ ] The arity of recursive-aggregate relations must be greater than or equal to two.
- [ ] The type of the last attribute cannot be of type symbol if the aggregation is a sum
- [ ] If the type of the last attribute is symbol, and the aggregation is min/max perhaps a warning should be issued that this is not the usual lexorder.

**Comment by b-scholz** [comment]
Please bring the source files into the right format using `clang-format -i <file>`. Following source files are not formatted:
```
src/RelationTag.h
src/synthesiser/Relation.h
```

**Comment by b-scholz** [comment]
Please also check whether I/O is working. The auxiliary arity of one may hide the last column.

**Comment by remysucre** [comment]
> Please also check whether I/O is working. The auxiliary arity of one may hide the last column.

I/O is working fine - all attributes are printed.

**Pull request closed without merging**
