### PR TITLE
Allow concatenation of IODirective filename to facts-dir

### PR DESCRIPTION
**Pull request by anantoni**
Change in RamTranslator in order to concatenate the filename provided from an input directive to the facts dir provided through the command line as long as that filename is not absolute.

Since the -F flag is ignored when providing an .input IO directive and the compiler does not concatenate stringified constants from the preprocessor located next to strings I made the change in order to provide flexibility to the naming of .facts files under the facts-dir provided through the command line. In case the filename is absolute the facts-dir is ignored, whereas in case the facts-dir string is empty the current procedure is followed.

However, I am not sure whether this is the best way to handle this issue.

### CODE REVIEW

**Comment by mmcgr** [comment]
The current .input/.output test datalog files currently use a relative path from where the test script is run from. e.g.
```
.input A(IO="file",filename="../../syntactic/input_directive_quotes4/NameFromInputDec.facts",delimiter="g")
```
This is a different path to that given to -F. Changing the .input in this example to
```
.input A(IO="file",filename="NameFromInputDec.facts",delimiter="g")`
```
and moving the facts file to the facts directory, would make this test work with the changes. Something similar could be done for the other failing tests.

**Comment by anantoni** [comment]
Thanks, I totally forgot to rerun the tests after my changes. I think everything is ok now.

Regards,
Anastasios

**Comment by b-scholz** [comment]
Martin changed the formatting rules of the project. Every check needs to comply now to the formatting rules dictated by the llvm checker. Sorry for this hassle.

**Comment by anantoni** [comment]
It's no hassle really and it helps me become familiar with the whole process. I hope it's handled correctly now. I apologize for the inconvenience.

**Comment by b-scholz** [comment]
Thanks for contributing!

**Pull request merged**
