### PR TITLE
RAM transformation to reorder scans of relations and their deltas

### LINKED ISSUE #2232: Iterate over delta first when deleting for subsumption
Consider this program:
```
.decl r(n: number, m: number)
r(0, 0).
r(n+1, n+1) :- r(n, n), n < 10.
r(m, n) <=
  r(n, p) :-
    n < p.
.output r(IO=stdout)
```
Here's the portion of the RAM program that schedules tuples to be deleted:
```
   DEBUG "r(m,n) <= r(n,p) :- \n   n < p.\nin file /mate/mate/breakout/sub.dl [4:1-6:11]"
    QUERY
     IF ((NOT ISEMPTY(r)) AND (NOT ISEMPTY(@delta_r)))
      FOR t0 IN r
       IF EXISTS t1 IN @delta_r ON INDEX t1.0 = t0.1 AND t0.1 <= t1.1 WHERE (t0.1 != t1.1)
        INSERT (t0.0, t0.1) INTO @delete_r
    END QUERY
   END DEBUG
```
Assuming that the delta is normally smaller than the full relation, this query plan is inefficient - it should instead iterate over `@delta_r` and do the containment check (`IN`) over `r`.

This principle is fairly general, so it might be nice to have a RAM->RAM transformation pass to do this. However, depending on the details of how subsumption is compiled, it might be easy to make a local switch for this specific case.

### PR DESCRIPTION
**Pull request by langston-barrett**
Canonical example:
```
.decl rel(n: number, n2: number)

rel(0, 1).
rel(0, 2).
rel(1, 2).

rel(n, m) :-
  rel(n, _),
  rel(m, _),
  m < n.
```
With the default SIPS, we currently get
```
   DEBUG "rel(n,m) :- \n   rel(n,_),\n   rel(m,_),\n   m < n.\nin file /mate/souffle/test.dl [15:1-18:9]"
    QUERY
     IF ((NOT ISEMPTY(rel)) AND (NOT ISEMPTY(@delta_rel)))
      FOR t0 IN rel
       FOR t1 IN @delta_rel ON INDEX t1.0 <= t0.0
        IF ((t1.0 != t0.0) AND (NOT (t0.0,t1.0) IN rel))
         INSERT (t0.0, t1.0) INTO @new_rel
    END QUERY
   END DEBUG
```
With this transformation, we get
```
   DEBUG "rel(n,m) :- \n   rel(n,_),\n   rel(m,_),\n   m < n.\nin file /mate/souffle/test.dl [15:1-18:9]"
    QUERY
     IF ((NOT ISEMPTY(rel)) AND (NOT ISEMPTY(@delta_rel)))
      FOR t0 IN @delta_rel
       FOR t1 IN rel ON INDEX t0.0 <= t1.0
        IF ((t0.0 != t1.0) AND (NOT (t1.0,t0.0) IN rel))
         INSERT (t1.0, t0.0) INTO @new_rel
    END QUERY
   END DEBUG
```
Fixes #2232

### CODE REVIEW

**Comment by b-scholz** [comment]
Can you implement this as a SIPS?

**Comment by langston-barrett** [comment]
> Can you implement this as a SIPS?

On #2153, you said:

> AST still contained utilities for checking delta relation. With the new ast-to-ram translator, delta relations are no further present in AST and hence Delta-SIPS and Delta utilities in AST need to be removed.

which made me think that this couldn't be done as a SIPS, and

> In future, scheduling should be done in RAM (not in AST).

which made me think that perhaps this shouldn't be done as a SIPS. Are the above statements no longer true or relevant?

**Comment by langston-barrett** [comment]
I'm also not sure that this can be written as a SIPS and also apply to the deletion portion of subsumptive rules, which was my primary motivation. That could probably be solved specifically in subsumption-related code, but it seems preferable to have a general solution such as this.

If this were implemented as a SIPS then it would either (1) force users to abandon their normal SIPS, which might perform quite well, or (2) we would have to make variants of the various SIPS, each of which does or does not take deltas into account. Moreover, I think this scheduling is a good default and shouldn't necessarily require users to understand and utilize non-default SIPS to gain the benefits.

**Comment by b-scholz** [comment]
Indeed, we cannot check delta in AST directly but we can still check this in SIPS with an extended interface. 
We know that the version is the position of the delta relation in the vector of atoms of the rule. 

Sam just uploaded his first version of his auto scheduler.  Static schedules are still important for profiling. Hence, we should look more carefully how to implement your Delta heuristic.

**Comment by langston-barrett** [comment]
> Moreover, I think this scheduling is a good default and shouldn't necessarily require users to understand and utilize non-default SIPS to gain the benefits.

Thinking on this more, I no longer believe this. It might be the case that the non-delta version has more bound variables (i.e., better indexes).

> Indeed, we cannot check delta in AST directly but we can still check this in SIPS with an extended interface.
We know that the version is the position of the delta relation in the vector of atoms of the rule.

Ok, I will see if I can find a way to implement something similar as a SIPS. That doesn't solve the inefficiency with subsumption, but maybe I can find another way to address that.

**Pull request closed without merging**
