### PR TITLE
Implement no_magic and no_inline relation qualifiers

### PR DESCRIPTION
**Pull request by sharon-wang**
Currently, we have relation qualifiers `magic` and `inline` to enable magic-set and inlining (respectively) for relations. This PR introduces relation qualifiers `no_magic` and `no_inline` to disable magic-set and inlining for relations. Additionally, options `inline-exclude` and `magic-transform-exclude` are introduced.

Note that
- `no_inline` overrides `inline` (when used on the same relation)
- `no_magic` implies `no_inline` on a relation
- `magic-transform-exclude` implies `inline-exclude` on the specified relations
- `inline-exclude` takes precedence over other modifiers

Documentation PR: https://github.com/souffle-lang/souffle-lang.github.io/pull/85.

cc @OlivierHamel

### CODE REVIEW

**Comment by b-scholz** [comment]
Can you run `clang-format -I <file-names>` for your source-code? This guarantees that the source code looks uniformly in this project.

**Comment by b-scholz** [comment]
Or change manually
```
diff --git a/src/ast/transform/InlineRelations.cpp b/src/ast/transform/InlineRelations.cpp
11
index 1ec47e4..02c2462 100644
12
--- a/src/ast/transform/InlineRelations.cpp
13
+++ b/src/ast/transform/InlineRelations.cpp
14
@@ -1054,9 +1054,8 @@ bool InlineRelationsTransformer::transform(TranslationUnit& translationUnit) {
15
         for (Relation* rel : program.getRelations()) {
16
             // Skip if the relation is going to be inlined or if no_inline or no_magic is present
17
             if (rel->hasQualifier(RelationQualifier::INLINE) ||
18
-                rel->hasQualifier(RelationQualifier::NO_INLINE) ||
19
-                rel->hasQualifier(RelationQualifier::NO_MAGIC)
20
-            ) {
21
+                    rel->hasQualifier(RelationQualifier::NO_INLINE) ||
22
+                    rel->hasQualifier(RelationQualifier::NO_MAGIC)) {
23
                 continue;
24
             }
25
```

**Comment by b-scholz** [comment]
Sharon/Olivier -- can you explain the semantics of this qualifiers in more detail? I understand that the `no_magic` is useful (for  `--magic-transform=*`). However, I don't understand the qualifier `no_inlining` - can you explain?

**Comment by b-scholz** [comment]
I cannot reformat the source code on my side; you need to reformat, add, commit, and push the changes. Sorry for this.

**Comment by sharon-wang** [comment]
> Sharon/Olivier -- can you explain the semantics of these qualifiers in more detail? I understand that the `no_magic` is useful (e.g., the programmer sets the command-line option `--magic-transform=*`). However, I don't understand the qualifier `no_inlining`. For which use case is this useful - can you explain?

`no_inline` currently
- overrides `inline`
- is implied by `inline-exclude`, `no_magic` and `magic-transform-exclude`

upcoming work
- auto-inlining/file-level inlining option (eg. `inline-include`), where `no_inline` is used to opt out of inlining specific relations

With this PR, a developer may not benefit very much from `no_inline`, but with the introduction of an inlining option, it would be used on relations to skip inlining them.

**Comment by OlivierHamel** [comment]
To clarify, future PRs will expand on the inliner:
a) A heuristic analysis that decides if a relation are worth inlining. This is the main use case for `no_line` (overrides the heuristic).
b) The no-cycles in inliners restriction is weakened. If there's an inlining cycle, the transform will attempt to break the cycle by ignoring a subset of inline-specified recursive atoms. This doesn't weaken inlining guarantees for existing code since they're currently required to be acyclic.

**Review by b-scholz — APPROVED** [review]

**Comment by b-scholz** [comment]
Thanks for the contribution!

We would need to improve the documentation of this PR.
Next, I will comment on souffle-lang.github.io.

**Pull request merged**
