### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by mmcgr**
Updating the changelog with changes since the last release. There have been a lot, so the list does need review - I'm sure I've missed some or oversimplified others.

### CODE REVIEW

**Comment by b-scholz** [comment]
I will check tomorrow.

**Comment by b-scholz** [comment]
I went through the log. You may want to mention: 
- Distributions - ARM/updates of old ones/etc (mmcgr)
- Improve Program Minimiser(azreika)
- Unrestricted number of columns per relation (before set to 64) (sam)
- Generative functors (ohamel)
- Refactor parser (ohamel)

**Comment by mmcgr** [comment]
codecov seem to have broken their upload script. I'll disable the coverage requirement for now.

**Comment by b-scholz** [comment]
Oh dear.

**Comment by mmcgr** [comment]
I think the testing gods are messing with me now. Travis test have passed, yet are also queued forever ...

**Pull request merged**
