### PR TITLE
fix btree destructors #2127

### PR DESCRIPTION
**Pull request by julienhenry**
Fixing destructor issues on the Btree datastructures.
Related to https://github.com/souffle-lang/souffle/pull/2130 https://github.com/souffle-lang/souffle/issues/2127

### CODE REVIEW

**Comment by julienhenry** [comment]
Related to https://github.com/souffle-lang/souffle/pull/2130

**Comment by b-scholz** [comment]
Unfortunately, a VTABLE (introducing a virtual destructor for class node) will slow us down - specifically for clearing memory. We would need some static means to fix this. We would need something like this:
https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern

**Comment by julienhenry** [comment]
Here is another attempt. Before calling delete, we check if this is an inner node or leaf node. If this is an inner node, make sure to reset its children to make sure they do not get deleted.

**Review by b-scholz — APPROVED** [review]
Thanks for fixing the bug!

**Pull request merged**
