### PR TITLE
Splitting the generated C++ Code into multiple files to improve compile-time

### PR DESCRIPTION
**Pull request by julienhenry**
On large souffle projects, the compile time of the generated C++ can be very long. Every single small change in datalog requires recompiling the entire C++ code, which is very inefficient. 
This pull request is an attempt to have a more flexible synthesiser, that allows to generate the C++ code in multiple files: the code generation decomposes the code in several classes:
- one class per specialized datastructure, as it was already the case before
- one class per subroutine
- one class for the "main" class, i.e. the one that is calling the subroutines in the right order.

The goal is to have all these classes as decorrelated as possible. In particular, we don't want to recompile a subroutine 'i' if we only changed the datalog code of subroutine 'j'. Consequently, subroutine classes are constructed by passing them a reference to the relations and user-defined functors that they need to use. A datalog code change that does not modify a given subroutine will produce the exact same C++ file for that subroutine.
Also, moving the implementation of the specialized data-structures in their own cpp files will prevent from needing to compile them each time we include their header.

When generating the code in multiple files, the first compilation takes longer than with a single file, but once this is done, and when changing only a few rules/relations of the datalog code and recompile, the recompilation is much faster than the single-file version. 
To give an idea on our Souffle code : 
- single-file compilation time: ~15min
- multiple-file compilation time (first time) and -j8 : ~10min
- multiple-file incremental compilation time (after small edits in .dl files) and -j8 : 1min30s

### CODE REVIEW

**Comment by b-scholz** [comment]
That is great work. I just wonder the gains w.r.t. compile-speed for small changes in programs.

We have typedefs for data-structures; we have strata with relations as member variables; we have rules that use either relations from the own strata or relations from already computed strata. 

If I understand your WIP correctly, the gain is to compile the strata whose rules have changed and not the whole program. 
By doing so, the compiler has only a subset of data-structures, relations, and rules to compile. 

Can we do another PR for the new functor interface? That is better in terms of SWENG.

**Comment by julienhenry** [comment]
Yes, I will discard the changes related to the functors interface and do a dedicated PR later. 
Indeed, this PR was intended to split the generated code into several pieces to help with "incremental" compilations where only a small amount of relations/rules have changed. 
The typical scenarios while developping a soufflé analysis where we want to avoid a full recompilation of the entire datalog code are:
(1) When I create a new relation / remove a relation
(2) When I write a new rule / remove a rule / slightly change an existing rule
(3) When I add/remove a new user-defined functor

Isolating each stratum in its own c++/header file is a good first step to address the above 3 points, because it ensures that any stratum that is not affected by some datalog changes will produce the exact same c++ code. 
Strata classes will have as member variables a reference to:
- relations that are used
- relations that are populated
- user-defined functors used

To make sure the generated C++ code of an un-modified stratum does not change, I had to get rid of some non-determinism at some places in Soufflé in particular: 
- avoid the use of std::set<Relation*> whose order depends on memory addresses
-  avoid naming c++ identifiers with a counter : rel_1_A, rel_2_B, rel_3_C ,etc. , since adding/removing a relation will change the name of many other relations => rel_1_A, rel_2_AA, rel_3_B, rel_4_C ...

**Comment by b-scholz** [comment]
Is it possible to keep the old functionality (source code in a single file) and the new one (splitting the C++ for each stratum) or is this too much of an effort?

**Comment by julienhenry** [comment]
> Is it possible to keep the old functionality (source code in a single file) and to have the new one (splitting the C++ for each stratum) as well? Or is this too much of an effort?

Yes, the idea is to have two modes: a single-file output and a multiple-files output. The single-file output should remain the default, while the other could be for more advanced users ?

**Comment by b-scholz** [comment]
Is it done?

**Comment by julienhenry** [comment]
@b-scholz I believe this pull request is now in an acceptable state to be reviewed.

**Comment by b-scholz** [comment]
Great job - I will have a look!

**Comment by b-scholz** [comment]
I look at the changes now. Great work. I like the refactoring.

Have you done performance testing? I also do not understand why the interpreter is affected by this change.

**Comment by julienhenry** [comment]
The interpreted is affected because I renamed subroutines/strata to avoid using their SCC id number in their name, as the SCC id number changes too often when we modify the datalog code.
I did not notice any performance changes in our code, but I haven't done a proper performance evaluation to see how that affects the performance of the generated code... Intuitively I don't see why that would change anything (the generated code of subroutines has not changed)

**Review by b-scholz — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
