### PR TITLE
Add option to explicitly enable frequency counter in profiler.

### PR DESCRIPTION
**Pull request by XiaowenHu96**
The frequency counter causes a lot of performance overhead under profiling mode. This makes the reported execution time inaccurate.

This PR disables the frequency counter by default so that user can at least get accurate profiling for the execution time.
If the frequency counter is desired, the user should pass `--profile-frequency` along with `--profile` to enable the counter.

Once the PR is merged I'll update the documentation accordingly.

### CODE REVIEW

**Comment by b-scholz** [comment]
Please can you update the documentation on souffle-lang.github.io. We need to explain the new flag for the interpreter. The synthesiser has by default frequencies generated.

**Review by b-scholz — DISMISSED** [review]

**Comment by XiaowenHu96** [comment]
> Please can you update the documentation on souffle-lang.github.io. We need to explain the new flag for the interpreter. The synthesiser has by default frequencies generated.

Just to clarify, with this PR, frequency is disabled in BOTH interpreter and synthesiser by default.
If we want the frequency to be by default enabled in synthesiser but disabled in the interpreter, I can make a quick change.

**Comment by b-scholz** [comment]
Sorry - I did not pick up the changes in the synthesiser. Great!

**Review by mmcgr — APPROVED** [review]

**Comment by mmcgr** [comment]
I think you need to add the new flag at `tests/profile.at:52`

**Comment by b-scholz** [comment]
Test cases fail due to lack of frequencies I guess:
```
05: lrg_attr_id   -c -j8                            souffle-profile -c "rul C2.1" FAILED (profile.at:74)
725: recursive   -c -j8                            souffle-profile -c "rul C2.1" FAILED (profile.at:75)
```

**Review by mmcgr — APPROVED** [review]

**Pull request merged**
