### PR TITLE
Btree delete

### PR DESCRIPTION
**Pull request by thomas-seed**
Added BTreeErase.h as a copy of BTree.h but with the following modifications:
- Changed btree iterator to be a bidirectional iterator, also allowing public access to the node and position, as well as modification of the underlying tree.
- Added functionality for the erase operation. The main entry point has signature size_type erase(const Key& k). Erase is supported both for sets and multi-sets. For multi-sets, all keys equal to the given key are erased. The code basically follows the implementation in the google btree.

### CODE REVIEW

**Comment by b-scholz** [comment]
Please don't merge this pull request!

**Comment by mmcgr** [comment]
I've added a rule to require approval on this branch

**Comment by thomas-seed** [comment]
@b-scholz I have a couple of questions on your requests:
1. I can just change the pull request so that diff is computed against the master branch rather than the btree-delete branch. Then, only BTree.h will show up in the PR. Is this what you mean? Or do you want me to actually drop the additional commits? 
2. I assume you want me to keep BTree.h in its original form and add BTreeErase.h as an additional file? 
Thanks.

**Comment by b-scholz** [comment]
1) Yes. In addition, do you have some test cases as well?
2) Yes. The idea is to keep BTreeErase.h as a separate data-structure which will be used only when there is the need for deletion.

**Comment by b-scholz** [comment]
Thanks for the contribution!

**Comment by thomas-seed** [comment]
@b-scholz Sorry, I didn't see you had approved the changes. I've just squashed some commits, no other changes.

**Comment by b-scholz** [comment]
That's great. It could be that the continuous testing fails because of formatting issues. 
Please can you run `clang-format -I BTreeErase.h` as well.

**Comment by thomas-seed** [comment]
I just tried it but it didn't update the file so it must have been formatted okay already

**Comment by b-scholz** [comment]
That is great - it will let us know quickly.

**Comment by thomas-seed** [comment]
Okay great! Let me know if there are any more issues.

**Pull request merged**
