### PR TITLE
Changed printStatistics->printHintStatistics in synthesiser.

### PR DESCRIPTION
**Pull request by azreika**
Souffle currently crashes when `-v` is run with `--profile` in the compiled version. This PR fixes a typo which solves the problem.

### CODE REVIEW

**Review by mmcgr — APPROVED** [review]

**Comment by b-scholz** [comment]
This is my crime most likely. 
The issue is that we don't just print hint statistics - we print now the full information.
Hence, changing the name to print statistics is a misnomer - can we make it work with printStats?

**Review by b-scholz — CHANGES_REQUESTED** [review]
Can you find out why it is not working with printStatistic?

**Comment by b-scholz** [comment]
I believe that I found the problem. 
Please can you change in the header file `include/souffle/CompiledSouffle.h` the definition of nullary relations from printHintStatistitcs() to printStatistics(). That may solve your problem.

**Comment by mmcgr** [comment]
I think the string prefix also needs removing. Should the info relation also be modified in the same way?
```diff
diff --git a/src/include/souffle/CompiledSouffle.h b/src/include/souffle/CompiledSouffle.h
index ef06f37f..c946d56d 100644
--- a/src/include/souffle/CompiledSouffle.h
+++ b/src/include/souffle/CompiledSouffle.h
@@ -238,7 +238,7 @@ public:
     void purge() {
         data = false;
     }
-    void printHintStatistics(std::ostream& /* o */, std::string /* prefix */) const {}
+    void printStatistics(std::ostream& /* o */) const {}
 };
 
 /** info relations */
@@ -323,7 +323,7 @@ public:
     void purge() {
         data.clear();
     }
-    void printHintStatistics(std::ostream& /* o */, std::string /* prefix */) const {}
+    void printStatistics(std::ostream& /* o */) const {}
 };
```

**Review by b-scholz — APPROVED** [review]

**Pull request merged**
