### PR TITLE
Move I/O system to the io directory

### PR DESCRIPTION
**Pull request by b-scholz**
This PR moves the I/O related source files to the io directory. 
This is related to issue #462.

### CODE REVIEW

**Comment by b-scholz** [comment]
I am confused about the distcheck run
```
compiler error: cannot compile source file ./souffleQjqJ8E.cpp
g++ -std=c++17   -fwrapv  -DUSE_NCURSES  -O3 -DUSE_LIBZ  -DUSE_SQLITE  -fopenmp  -march=native  -std=c++17  -o/souffle/souffleQjqJ8E ./souffleQjqJ8E.cpp  -ldl -lpthread -lsqlite3 -lz -lncursesw -I/tmp/souffle/bin/../include
In file included from ./souffleQjqJ8E.cpp:2:
/tmp/souffle/bin/../include/souffle/CompiledSouffle.h:22:10: fatal error: souffle/IOSystem.h: No such file or directory
   22 | #include "souffle/IOSystem.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
failed to compile C++ source <./souffleQjqJ8E.cpp>
```

I would have assumed that the include-directory would have been prepared and would contain the copied headers from `io`.

**Comment by mmcgr** [comment]
If you have a look at how the Makefile deals with the utility directory it demonstrates how to make this work. My earlier PR that made an io directory may be a better demonstration, but does contain some other changes that may make it harder to follow.

**Comment by mmcgr** [comment]
Actually, in your implementation you had a slightly different approach so I'm not sure what I said applies directly. The problem is that the files don't exist because they're not in the list of sources in the Makefile. Renaming them in the public headers so they're still in an io subdir may be enough.

**Comment by b-scholz** [comment]
I made the changes - fingers crossed it works.

**Pull request merged**
