### PR TITLE
cache regex compilation

### PR DESCRIPTION
**Pull request by strRM**
We have run into some issues with regex constraints. Our program needs to be make use of the regex constraint, but we quickly noticed that it led to quite a slowdown. The runtime of our program was around 100 seconds and I tracked it down to the fact that regexes are compiled each time a match is performed. We decided to cache the construction of the regexes, of which there are very few, and this reduced the runtime to less than one second.  

This patch introduces a new data structure called ConcurrentCache, which a thin wrapper around the existing concurrent hashmap. Presently, the cache is always generated by the compiler, but I think that is something we can change later, possibly making it optional.

### CODE REVIEW

**Comment by b-scholz** [comment]
Can you reformat the code with clang-format or apply the changes from here:
https://github.com/souffle-lang/souffle/actions/runs/3289357677/jobs/5421102088

**Comment by strRM** [comment]
Sorry about that. I was using clang-format which is version 14 on my host, but it looks like github CI uses 11.

**Comment by strRM** [comment]
Looks like there may be an issue with noomp. I'll dig into it, but I would appreciate a hint if there is anything obvious that I'm doing wrong.

**Comment by quentin** [comment]
An alternative design that would avoid introducing a dedicated data structure would be:
- for the interpreter, store the prepared regex in the appropriate `interpreter::Node` (maybe of a new kind), like it was done for FFI callbacks stored in the `FunctorNode` for instance.
- for the synthesizer, store the prepared regex as a field of the generated class.

**Comment by strRM** [comment]
I added code along the lines you had suggested, but I left the cache alone. So, in aggregate, this update provides fast access to constant regexes (probably the majority) and a cache for fast evaluation of dynamic regexes.

I created a RegexConstant, which replaces a StringConstant when processing a MATCH/NOT_MATCH constraint. When interpreting MATCH/NOT_MATCH I check if the pattern is a regex, otherwise the existing code is executed.

I could not think of a better way to do this right now.

**Review by b-scholz — APPROVED** [review]
Thanks for the contribution! Great job!

**Comment by strRM** [comment]
Thanks. This helps us a lot, too.

**Pull request merged**
