### PR TITLE
Print profile events live

### PR DESCRIPTION
**Pull request by mmcgr**
Print profile events asynchronously, and reasonably live.

### CODE REVIEW

**Comment by souffle-lang** [comment]
[64% (0.0%) vs master 64%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-GCC7-Coverage/7/)

**Comment by souffle-lang** [comment]
[64% (-0.01%) vs master 64%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-GCC7-Coverage/8/)

**Comment by souffle-lang** [comment]
[64% (-0.01%) vs master 64%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-GCC7-Coverage/9/)

**Comment by codetaro** [comment]
That's the 3fd

**Pull request merged**
