### PR TITLE
Sum type support

### PR DESCRIPTION
**Pull request by ohamel-softwaresecure**
Adds support for sum types, aka tagged unions. Sum types are desugared to `(branch-id, branch-value)` records.

Changes:
+ sum types (init syntax: `@<name> <branch> <value>`)
+ sugar is included for Haskell style ADTs.
+ record init exprs can now be prefixed by `@ <name> [ ... ]` to specify the record type

Demo program:
```
.type NullRecord = []
.type ADT
  = A0 = NullRecord   // branches can refer to existing types
  | A1 []             // or declare a record inline. inlined implicitly declares a record type with the same name.
  | B  = symbol
  | C  = symbol       // branches can have the same RHS, but not the same name
  | D  [ c0: symbol, c1: number ]
  | E  [ e0: number ]
  | F  = number

.decl d(x: D)         // can use the record type of an ADT-styled sum branch
d([ "foo", 5 ]).
d(@D [ "bar", 100 ]). // explicitly specify record type (optional)

.decl a(result: ADT)
a(@ADT A0 []).
a(@ADT A1 x) :- x = [].
a(@ADT B "hello").
a(@ADT C "bye").
a(@ADT D x) :- d(x).
a(@ADT E [ -1 ]).
a(@ADT E [ -5 ]).
a(@ADT F 6 * 9).

.decl b(result: number)
b(x) :- x < -2, a(@ADT E [ x ]).
b(x) :- a(@ADT D [ _, x ]).
b(x) :- x = 42, a(@ADT F x).

.output a
.output b
```

I expect some amount of bike-shedding, particularly with the record/sum init syntax.

TODO: Ideally some syntax sugar for automatically lifting records to branches (when unambiguous) would be nice. e.g.
```
.type MaybeNum = None [] | Some [ x: number ]
.decl a(x: MaybeNum)
a([ 5 ]). // automatically lift record to sum init

.type Ambig = Foo [ x: number ] | Bar [ x: number ] | Baz [ x: string ]
.decl b(x: Ambig)
b([ 5 ]). // ERROR: ambig between `Foo` and `Bar`
b([ "x" ]). // OK: only one branch matching record `[ string ]`
```

TODO: test cases

### CODE REVIEW

**Comment by olligobber** [comment]
I was going to do something like this, thanks for saving me the effort. Looks cool.

**Comment by mmcgr** [comment]
Jenkins, test this please

**Comment by ohamel-softwaresecure** [comment]
There are a number of optimizations that can be easily added at a later time:
1) `RemoveRelationCopiesTransformer` should to be made aware of sum types. I'll wait for PR #1306 to be merged first.
2) Enum-style (all branches are zero-arity records) ADTs should be desugared to constant values (see below).
3) Enum sugar: extend parser to accept enum-like ADTs. Haskell-syntax for this clashes with current syntax for unions. Add new syntax? : e.g.
```
.data E = A | B | C | D
```
4) New-type desugar: non-recursive single branch w/ 1-arity should desugar to just the branch value's payload. See below.

A few record improvements are easy fruit too and would complement the above:
5) Zero-arity records should always be lowered to some trivial constant (`nil` would do).
6) Non-recursive 1-arity records should be erased and replaced by their payload. People with strange urges to do manual Peano arithmetic should still be able to do it with recursive 1-arity.

**Comment by azreika** [comment]
Can you post a high-level example of what you're aiming for with the desugaring for clarity? What is the intended equivalent Datalog program after desugaring for the first program?

**Comment by ohamel-softwaresecure** [comment]
Given the program:
```
.type NullRecord = []
.type ADT
  = A0 = NullRecord   // branches can refer to existing types
  | A1 []             // or declare a record inline. inlined implicitly declares a record type with the same name.
  | B  = symbol
  | C  = symbol       // branches can have the same RHS, but not the same name
  | D  [ c0: symbol, c1: number ]
  | E  [ e0: number ]
  | F  = number

.decl d(x: D)         // can use the record type of an ADT-styled sum branch
d([ "foo", 5 ]).
d(@D [ "bar", 100 ]). // explicitly specify record type (optional)

.decl a(result: ADT)
a(@ADT A0 []).
a(@ADT A1 x) :- x = [].
a(@ADT B "hello").
a(@ADT C "bye").
a(@ADT D x) :- d(x).
a(@ADT E [ -1 ]).
a(@ADT E [ -5 ]).
a(@ADT F 6 * 9).

.decl b(result: number)
b(x) :- x < -2, a(@ADT E [ x ]).
b(x) :- a(@ADT D [ _, x ]).
b(x) :- x = 42, a(@ADT F x).

.output a
.output b
```

The (current) de-sugaring is:
```
.type NullRecord = []
// original decl
// .type ADT
//   = A0 = NullRecord                 // branch-id = 0
//   | A1 []                           // branch-id = 1, implicitly defines record type `A1`
//   | B  = symbol                     // branch-id = 2
//   | C  = symbol                     // branch-id = 3
//   | D  [ c0: symbol, c1: number ]   // branch-id = 4, implicitly defines record type `D`
//   | E  [ e0: number ]               // branch-id = 5, implicitly defines record type `E`
//   | F  = number                     // branch-id = 6
// desugared into
// inline record branches implicitly create record types
.type A1  = []
.type D   = [ c0: symbol, c1: number ]
.type E   = [ e0: symbol ]
.number_type ADT_BranchID
.type ADT = [ branch_id: ADT_BranchID, branch_value: ⊤ ]

.decl d(x: D)
d(@D [ "foo", 5 ]).   // type constraint solution is type `D`
d(@D [ "bar", 100 ]). // no change, type was explicitly given

.decl a(result: ADT)
a(@ADT [ 0, [] ]).
a(@ADT [ 1, x ]) :- x = [].
a(@ADT [ 2, "hello" ]).
a(@ADT [ 3, "bye" ]).
a(@ADT [ 4,  x ]) :- d(x).
a(@ADT [ 5, -1 ]).
a(@ADT [ 5, -5 ]).
a(@ADT [ 6, 6 * 9 ]).

.decl b(result: number)
b(x) :- x < -2, a(@ADT [ 5, [ x ] ]).
b(x) :- a(@ADT [ 4, [ _, x ] ]).
b(x) :- x = 42, a(@ADT [ 6, x ]).

.output a
.output b
````

Potential future improvements includes:
1) de-sugaring non-recursive 1-arity records into their payload: `[ x ]` -> `x`
2) de-sugaring 0-arity records by erasing them entirely (minor complication w/ 1-arity relations whose argument is the zero-arity record).
3) de-sugaring non-directly-recursive sum-types with a single branch into their RHS: `.type T = T1 = T2` -> `.type T = T2`

**Comment by b-scholz** [comment]
Hi - can we arrange a meeting to talk about this? 
My email is Bernhard.Scholz@sydney.edu.au.

**Comment by b-scholz** [comment]
We had more discussion at USYD about ADT. We feel that for the sake of consistency, union types are the right way forward as a first step. The rationale is that we have introduced union types for primitive types some time ago and it might be confusing that we have different typing strategies.

Said this, we feel we can simulate ADTs with union types having a small little tweak. As discussed, we have following problem:

```
.type X = A | B 
.type A = [...]
.type B = [...]
```

Type X would have a purely syntactic typing behavior in our system. To make it dynamic as perhaps needed for ADT translation, we would need to box type X. 
```
.type X = [box: A | B] 
.type A = [...]
.type B = [...]
```

If we implement it well, simple boxing (over a single field) may be implemented very efficiently (i.e. without a double lookup).

Records in a union class are mapped to a single record (as you demonstrate for ADTs and as it is implemented in our type-system branch from last year). For simple boxed types, we can carry some additional flags in the type identifier field. 

After implementing polymorphic union types, we are quite open-minded to implement ADTs if the need arises. For us, this is only a question of prioritization.

**Comment by ohamel-softwaresecure** [comment]
I've some questions regarding the semantics of heterogeneous unions but first, to ensure I understood correctly:

1) Core: Add support for structurally-heterogeneous unions via the same tagged-box mechanism as the PR.
2) Ergonomics: Automatically box/unbox as required. (AST transform)
3) Ergonomics: Filter branches when unifying with another union.
4) Optimization: Elide boxing when union branches are subtypes of the same type. (e.g. numeric type)
5) Optimization: Flatten boxed single-element non-recursive records. (Extra, needed for below.)

Given the above, keeping the proposed ADT syntax/behaviour above requires only the syntax changes + desugaring each branch into a 1-record.

**Questions: **
Consider the following type declarations:
```
// two disjoint subsets of `number`
.type S_a <: number
.type S_b <: number

// nominally distinct, structurally equiv
.type R2_a  = [ x: string, y: number ]
.type R2_b  = [ x: string, y: number ]
// and a structurally distinct record
.type R1    = [ x: S_a ]

//  hypothetical generalisation of disjoint subtypes to any record type
.type R2_a_a <: R2_a
.type R2_a_b <: R2_a

.type USub_S  = S_a | S_b         // union of non-record primitive subtype
.type USub_R  = R2_a_a | R2_a_b   // NEW: union of generalised subtypes
.type UHet_R2 = R2_a | R2_b       // NEW: heterogenous union of structurally equiv types
.type UHet_R1 = R2_a | R1         // NEW: heterogenous union of structurally equiv types
// NEW: Kitchen sink
.type USink   = S_a | S_b | R2_a | R2_b | R1
```

**Comment by b-scholz** [comment]
Can we move this discussion (copy text and keep link to this PR) to an issue in the issue list and close this PR?

**Comment by b-scholz** [comment]
I contemplated more about this issue and I take it back what I said related to unions.
Indeed, it would be nice to have one typing strategies such as union types for records as well. 

However, we have chosen a certain path in our implementation that makes union types for records extremely difficult. The reason for this is that the reference domains of record types of different arities are not shared.  For finding a feasible, implementation,  we need to introduce a super-union type for records carrying all potential types and a selection field similar to the proposal above. Also, this was prototyped, in the typesystem branch of souffle a while ago. Using the super-union type idea causes more issues in its implementation because the types of the union can exist outside the union and in the union record stored in a different format. 

To ease the implementation (and ultimately complexity),  I would suggest going ahead with ADTs / classical Pascal variants, etc.  I would only suggest changing the syntax slightly in operating with these variant records.

My proposal would be the following:

```
.type record = [x:number, y:list]
.type variant = [x:number | y:symbol | z:record]
```

`record` is a normal record; `variant` is a variant but it is declared using the separator instead of the comma symbol. This is the closed type - this means that we cannot extend it with another type like we could with the union semantics. The selection is fixed in that sense. 

I would prefer using the identifier of the fields to do the selection. For example,

```
.decl A(x:variant)

A([x:10]). 
A([y:"hello"]).
A([z:[10,nil]]). 
```

I need to check whether this works with the parser.

**Pull request closed without merging**
