### PR TITLE
Let `to_number` infer the base

### PR DESCRIPTION
**Pull request by bens**
This lets `x = to_number("0x100")` parse as 256, not 0. Similarly, binary literals are supported as `0b10010`.

### CODE REVIEW

**Review by quentin — COMMENTED** [review]
Nice, does this also work for numbers read from `.input` sources ?

**Comment by bens** [comment]
> Nice, does this also work for numbers read from `.input` sources ?

It seems to already work, see `tests/semantic/load9/facts/HexUnsigned.facts`.

**Comment by bens** [comment]
Do I need to make the PR from a non-master branch? I didn't think of that at the time.

**Review by quentin — APPROVED** [review]

**Comment by quentin** [comment]
Thanks for this contribution @bens

**Comment by quentin** [comment]
Nice to have: enhancement of the doc paragraph about `to_number` https://souffle-lang.github.io/arguments
See https://github.com/souffle-lang/souffle-lang.github.io

**Pull request merged**
