### PR TITLE
Improved Provenance

### PR DESCRIPTION
**Pull request by taipan-snake**
- Removed naive record provenance
- Check to stop multithreading and provenance being enabled at the same time
- Improved parsing for provenance explain query interface

### CODE REVIEW

**Comment by mmcgr** [comment]
This PR has problems with clang on travis. I believe it's not a problem with your code, but with an outdated libc++. I'll see if this can be improved without hacking at perfectly valid code.

**Comment by b-scholz** [comment]
I had a quick read. Your merge most likely fails because an old GCC lib may be used. We need GCC >=4.9.

**Comment by mmcgr** [comment]
I tried using a more recent version of the GCC lib, and this leads to issues with pthreads. The regex_iterator problem is gone, but now there are linking errors with pthread. We need pthreads because clang with a new gcc library uses pthreads to support std::thread which is used by the profiler.

I want to find a fix that doesn't involve installing a new gcc alongside clang and adding back in pthread dependencies. This may not be practical, though.

Finding an approach that doesn't use regex_iterator also works, for now, but this issue may arise again.

**Comment by b-scholz** [comment]
That is interesting perhaps we can discuss this on Monday.

**Comment by b-scholz** [comment]
It is related to parsing of the explain command. I believe a small little parser can be written by hand if that helps.

**Comment by b-scholz** [comment]
I have created a new .travis.yml that requires a newer version for g++, i.e., version 7. 
There might be still one problem left, i.e., convincing travis to use the latest version rather than default version. We could do this perhaps with the commands:
update-alternatives --set gcc "/usr/bin/gcc-7
update-alternatives --set g++ "/usr/bin/g++-7

**Comment by mmcgr** [comment]
Now that libstdc++ has been updated on travis, you're free to use any of the various regex versions you've tried. With the current testing backlog on travis you have a while to decide - otherwise I'll just merge the current version when the tests finally finish running.

**Pull request merged**
