### PR TITLE
First stage of AST->RAM translator refactoring.

### PR DESCRIPTION
**Pull request by azreika**
This PR significantly cleans up the ast2ram translation framework.

The primary goal of this stage was modularisation of the constructs, improved consistency, code simplification, and semantic reorganisation to make future refactoring stages easier. Most independent constructs have been taken out of the main translator file, and into their own ast2ram modules. Although not fully decoupled yet, a bulk of the hard work has been done. Additionally, most methods in the translator have been changed around/removed/created to reflect more semantically independent tasks. This makes the code much easier to read, follow, extend, and maintain. The provenance translator has also been moved into a subclass of the main translator, just overriding certain methods. This goal should be tackled further in a future PR.

Related to issues #1705 and #1709.

### CODE REVIEW

**Comment by mmcgr** [comment]
Looks like the json attributes we pass around internally is ordered non-deterministically, affecting output ordering. Either make the ordering deterministic, or modify the test.

**Comment by mmcgr** [comment]
#1746 should help with the failing json tests

**Comment by azreika** [comment]
Some provenance tests + `evaluation/match2` tests are failing but seems like it's only because of different ordering, as with the JSON tests. This should be standardised.

**Comment by azreika** [comment]
@mmcgr is there a way to see testsuite failure logs with the new testing framework? I figure this is a problem with the non-deterministically placed `.` in provenance test output, but want to check for sure.

**Comment by mmcgr** [comment]
Jenkins, test this please

**Comment by mmcgr** [comment]
> @mmcgr is there a way to see testsuite failure logs with the new testing framework? I figure this is a problem with the non-deterministically placed `.` in provenance test output, but want to check for sure.

This failure happened during the distcheck, which cleans up after itself. That makes it hard to produce output. Still, I've changed the settings to see if it can be debugged better and we'll see how that goes.

**Comment by azreika** [comment]
> > @mmcgr is there a way to see testsuite failure logs with the new testing framework? I figure this is a problem with the non-deterministically placed `.` in provenance test output, but want to check for sure.
> 
> This failure happened during the distcheck, which cleans up after itself. That makes it hard to produce output. Still, I've changed the settings to see if it can be debugged better and we'll see how that goes.

Perfect, thanks! The failure is from exactly the non-determinism that PR #1763 fixes, which is great news.

**Review by mmcgr — APPROVED** [review]

**Pull request merged**
