### PR TITLE
Record provenance

### PR DESCRIPTION
**Pull request by taipan-snake**
Fixed negation issue, and other small issues.

### CODE REVIEW

**Comment by mmcgr** [comment]
I think your git history was confused by the squashed merge into master. You can resolve the conflicts, or do a complicated rebase thing, but it might be easier to make a new branch from master and git cherry-pick the new commits.

**Comment by taipan-snake** [comment]
Okay, should I close and reopen this pull request?

**Comment by mmcgr** [comment]
If you're changing branch then there's no choice but to close and re-open.

**Comment by b-scholz** [comment]
David - there seems to be a conflict with the pull-request. Please can you have a look.

**Pull request closed without merging**
