### PR TITLE
Relations in souffle::SouffleProgram should be stored in sets rather …

### PR DESCRIPTION
**Pull request by MrNbaYoh**
…than vectors.

### CODE REVIEW

**Comment by b-scholz** [comment]
Great that you double-check the code. 

Note that this interface is used by the interpreter or the generated  C++ program. 

It is unlikely that a wrapper relation is added to the vector more than once. 

I would be very hesitant to change the interface from vector to set since we have other users of this interface. 

Can you explain why you need a set instead of a vector?

**Comment by lyndonhenry** [comment]
There are also performance considerations. `std::vector` is typically more performant than `std::set`, see [this link](http://users.cs.northwestern.edu/~riesbeck/programming/c++/stl-summary.html). Also, if using `std::set`, why not use `std::unordered_set`?

**Comment by MrNbaYoh** [comment]
@b-scholz I think sets would be more appropriate because with the current implementation when you call `souffle::SouffleProgram::getAllRelations` if there is a relation that is both an input and an output relation then it will be added to the resulting vector twice.

@lyndonhenry Actually using `std::unordered_set` would probably be better indeed.

**Comment by b-scholz** [comment]
I see - this is a bug and needs to be fixed. It is better to populate the vectors more carefully (avoiding duplicates) rather than changing the interface.

**Comment by b-scholz** [comment]
The basic idea would be to have a new vector  ```std::vector<Relation*> allRelations;``` that receives all relations. With that we don't get into the muddle we have at the moment. 

Would you like to do the change?

**Comment by b-scholz** [comment]
Thanks for the fix.

**Pull request merged**
