### PR TITLE
Remove input/output/computed/printsize from relations

### PR DESCRIPTION
**Pull request by mmcgr**
Remove IO information from relations and use the AST/RAM instead.

AstIODirectives are children of AstRelations, similar to AstClauses, so some IO related methods remain there. IO related qualifiers are also still handled, but will be removed when the long deprecated qualifiers are.

A followup PR will split AstIODirective into AstLoad and AstStore to match RamLoad/RamStore which will simplify things further.

### CODE REVIEW

**Comment by mmcgr** [comment]
I was debating whether or not to separate checking IO existence from the AstRelation, since the directives are children of the AstRelation, similar to AstClauses. If I add that now it will make any future AST restructuring easier.

**Comment by mmcgr** [comment]
Jenkins, test this please

**Comment by b-scholz** [comment]
Let's discuss when I am back. The idea is to separate data from operations. If it is too hard, we leave it as is.

**Comment by mmcgr** [comment]
The coding is not hard. It's more that an AstRelation is used not so much as a relation as a non-recursive stratum. That currently ties AstIO, AstRelation, and AstClauses together in the translator logic.

I'll leave dealing with that for a later PR.

**Pull request merged**
