### PR TITLE
Transform Redundant Sums

### PR DESCRIPTION
**Pull request by rdowavic**
Turn expressions of the form `sum k : { ... }` into `k * count : { ... }` with the `RemoveRedundantSumsTransformer`

### CODE REVIEW

**Comment by rdowavic** [comment]
I don't know why the checks don't run to be honest. How do I fix this?

**Comment by b-scholz** [comment]
It seems that plang1 is down. We need to restart the system.

**Comment by b-scholz** [comment]
jenko test please

**Comment by b-scholz** [comment]
This is related to issue #1092

**Pull request merged**
