### PR TITLE
Integration of flexible operator hints into btree implementation.

### PR DESCRIPTION
**Pull request by HerbertJordan**
Currently, it is set up to be equivalent to the old, single entry version. 

Have tested it on my system using a size of 2, 4, and 8 -- noticed some improvements in the hit rate in the unit tests. The integration test are still running, relying on travis :-)

### CODE REVIEW

**Comment by souffle-lang** [comment]
[64% (+0.06%) vs master 64%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/122/)

**Comment by souffle-lang** [comment]
[64% (+0.05%) vs master 64%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/123/)

**Comment by mmcgr** [comment]
The centos compiler bug can be worked around by moving the body of the operator in the error out of the class. Or at least the tests pass if you do.

**Comment by souffle-lang** [comment]
[64% (+0.05%) vs master 64%](http://plang1.it.usyd.edu.au/jenkins/job/PR-RHEL7-gcc7-Coverage/124/)

**Pull request merged**
