### PR TITLE
fix error handling and exit code

### PR DESCRIPTION
**Pull request by strRM**
We noticed that when our program invoked souffle via exec with incorrect data (actually CSV with newlines), souffle did not exit with an error status. I traced this down to two problems:

- the exit code of a sub-process was not properly passed around (leading to --compile not working right)
- loading an invalid facts file did not lead to a program error

### CODE REVIEW

**Comment by quentin** [comment]
Hi, thanks for this pull request.
I am wondering if we really want to exit on input error. Maybe the current behavior is expected?

**Comment by tgiannak** [comment]
Souffle already exits with an error code if the Datalog file has a syntax error or is otherwise unreadable. I would expect it to behave the same way if other input files (CSV, SQLite, etc.) are malformed or otherwise unreadable, so that I could tell programmatically that something had gone wrong.

**Comment by strRM** [comment]
I don't know, but if you cannot read the CSV file due a CSV syntax error (e.g. mismatched quotes), that seems like an error condition to me that users (e.g. other programs) should be told about. 

Test case for load3 actually contains this line in the stderr file:
`Error loading A data: Error converting <AA> in column 2 in line 2; cannot parse fact file A.facts!`

So, it is obviously treated as an error. It should be a warning if this isn't an actual error condition, IMO.

**Comment by quentin** [comment]
I get your point, I do agree Souffle should not even run the analysis and must eventually end with an error code. I am however challenging the "exit immediately and not showing every input file that cannot be read" as in [tests/semantic/load10/load10.err](https://github.com/souffle-lang/souffle/pull/2330/files#diff-34f739921545645cb37345f81fdd2b195b72b6dd567878b17cf148c21287eabb). But fair enough, it's only a nice to have.

**Comment by strRM** [comment]
Sorry, I was a bit unclear what you meant. I do also agree that it would be nice to delay exit and accumulate errors so as to provide a better user experience. 

I supposed I could add another commit to implement a delayed exit, but it might be better to do that as a separate MR.

**Comment by quentin** [comment]
Build errors on MacOS seems to be related to a change in Github runners from XCode 13 to XCode 14.

**Review by quentin — APPROVED** [review]
Thanks for the fixes!

**Review by quentin — APPROVED** [review]

**Comment by strRM** [comment]
We're happy to contribute as this helps us as well. I will try to get an update in so we can accumulate errors.

**Pull request merged**
