### PR TITLE
Concurrent symbol table and record table

### PR DESCRIPTION
**Pull request by quentin**
This introduces concurrent almost lock-free symbol and record tables.

The parallel utility class `MutexConcurrentLanes` provides a configurable number of access lanes and locking methods:
- lock/unlock a single lane with `lock(lane)/unlock(lane)`.
- acquire/release the capability to lock all other lanes with `beforeLockAllBut(lane)/beforeUnlockAllBut(lane)`.
- lock/unlock all other lanes once the capability is acquired/released with `lockAllBut(lane)/unlockAllBut(lane)`.

On top of the concurrent lanes mechanism, introduces a concurrent insert-only hash-map `ConcurrentInsertOnlyHashMap`. This hash-map allows concurrent lanes to search and insert values. When the datastructure must be resized, the resizing lane lock all other lanes and grows the map.

On top of the concurrent insert-only hash-map, introduces a concurrent insert-only bidirectionnal mapping datastructure `ConcurrentFlyweight` that associates an index to each distinct inserted key. This mapping allows concurrent lanes to search and insert keys or fetch a key from a mapped index. The internal hash-map associates a key to its index. And an internal array maps a key at its associated index position. When the datastructure must be resized, the resizing lane lock all other lanes and grows the index array. The datastructure is dimensioned with a number of handles that maintain per-lane state.

The `ConcurrentFlyweight` does not guarantee that all indexes are mapped between `0` and the last associated index. There may be a few holes (at most one per access lane). This is due to the index booking mechanism: when a lane detects that a key must be inserted, it books an index in the mapping for that key, but the actual insertion may not happen if a concurrent lane inserts the same key. If an index is not immediately used it is saved for the next insertion by the same lane (see `struct Handle`).

There is an OpenMP version of the `MutexConcurrentLanes` that associates one lane to one OMP thread. And a sequential `SeqConcurrentLanes` that maps all threads (technically the only thread) to the unique lane `0`.

This should be considered as a work-in-progress:
- number of lanes and handles should be aligned or at least number of handles should be `>=` number of lanes.
- number of handles could be specified on constructor instead of being part of the template arguments.
- remove unused `struct Handle` from `ConcurrentInsertOnlyHashMap`.
- release handle's `node` when `ConcurrentFlyweight` is destructed.
- check for other possible memory leaks.
- bring back comments that may have disappeared on API functions of the table.
- more performance benchmarks ?
- more robustness / soundness / concurrency tests ?
- tuning of hash-map load factor (fixed to `1.0` currently) ?

### CODE REVIEW

**Comment by quentin** [comment]
Relates to #1286

**Comment by b-scholz** [comment]
Our test infrastructure needs to be fixed. We need a timeout for each test case. Some of the tests did not terminate.
I cancelled them.

**Comment by b-scholz** [comment]
We still need to do some debugging. The memory and thread sanitisation failed.

**Comment by quentin** [comment]
Timeouts may be due to the template expansion time of the `RecordTable` that is by default `SpecializedRecordTable<0, ... ,12>`. Specializing record maps for arities 0 to 12 might be overkill. I wonder what is the typical frequency of record arities in programs.

**Comment by b-scholz** [comment]
I think that is fine. I stopped the execution after 3h runtime. I feel it was not related to the expansion. We need to do more debugging.

**Comment by b-scholz** [comment]
Several benchmarks failed for 32bit:
 - comp_inner_types (compiler, -j8)
 - func_in_rec (interpreter, -j8)
 - inline_nqueens (interpreter, -j8)
 - magic_nqueens (interpreter, -j8)

The situation is similar for the 64bit version.

**Comment by b-scholz** [comment]
The memory check revealed more benchmarks that have issues:
- func_in_rec
- records1
- records2

**Comment by quentin** [comment]
I don't know what went wrong with the last CI `post checkout` on Ubuntu CMake 32bit.
I am quite happy with the current state of this dev. Just missing some licence headers.

**Comment by HerbertJordan** [comment]
The code seems a bit convoluted, and its introduction is probably not improving maintainability.  

Since packing or unpacking any element at least requires the locking and unlocking of two mutexes (hidden in the lain implementation, once [here](https://github.com/quentin/souffle/blob/concurrent-tables/src/include/souffle/datastructure/ConcurrentFlyweight.hpp#L262), another time [here](https://github.com/quentin/souffle/blob/concurrent-tables/src/include/souffle/datastructure/ConcurrentInsertOnlyHashMap.hpp#L292)) the benefit of the actual lock free insertion into the hash map realized [here](https://github.com/quentin/souffle/blob/concurrent-tables/src/include/souffle/datastructure/ConcurrentInsertOnlyHashMap.hpp#L307-L345) is probably not very substantial. Benchmarks could show. Are there any results?

A typical way of building such a hash for concurrent access would actually be to apply sharding + a simple read/write lock per shard. You maintain N independent sequential hash tables and a read/write lock for each of those. When inserting a key, you hash the key and insert in the (hash % N)-th table by acquiring an [exclusive lock](https://en.cppreference.com/w/cpp/thread/unique_lock). For the lookup, you also hash the key and read from the respective hash table, using a [read lock](https://en.cppreference.com/w/cpp/thread/shared_lock). The code for this should be much simpler, you can use out-of-the-box data structures and locks, and if N is large enough and the hash function good, collisions and lock contention becomes unlikely.

Such a sharding approach would also resolve a problem I think the current implementation has: if the data structure grows, all threads attempting to read or write from the table are blocked until the resize is complete. The sharded version limits this by having completely independent tables. If this is still causing lock contention, there are ways to mitigate this further.

**Comment by quentin** [comment]
Hi,
On our workload we achieve results that satisfy us:
```
-j                        1    2    4     8
with critical section:   77s  70s  82s 104s  (current Souffle)
with concurrent tables:  74s  40s  23s  19s   (this PR)
```
On another workload:
```
-j                        1    2    4     8
with critical section:   3.0s  6.1s  9.9s 12.8s  (current Souffle)
with concurrent tables:  3.3s  2.0s  1.4s  1.2s   (this PR)
```
I cannot share the workload unfortunately. Note that they are real-case workload, not synthetic, and some preliminary effort was spent to optimize the souffle program itself. But I would be interested in running some of the benchmarks you use to validate Souffle performances.

The design requires to take up to 2 locks, these locks are contention free when each thread is allocated a separate access lane. All threads accessing the same data-structure are locked during a growing operation. There is probably a trade-off to study between memory consumption and the growth policy so that growing pauses are amortized.

The proposed design is based on our observation that our workload writes the record maps in non-negligible proportions and the exclusive write lock prevents scaling: in a preliminary work I re-used souffle's rw-locks on each individual record map but having a single writer at a time is too restrictive. This was also studied using Intel VTune. Our conclusion is that it is cheap and efficient to take two contention-free locks (even with grow pauses) compared to taking one rw-lock with frequent exclusive write mode.

I did not study a shard-based approach. Thanks for bringing that idea. If I understand it correctly it would require an exclusive write lock on each shard, so the number of shards must be large enough to probabilistically avoid contention. Would you suggest some literature demonstrating that kind of data-structure, the tuning options and the way growing is handled ? Also, how would you implement the reverse mapping (from index to data) ?

**Comment by b-scholz** [comment]
It is very strange that `Post checkout` fails. It executes the following commands:
```
Post job cleanup.
/usr/local/bin/git version
/usr/local/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/local/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || 
/usr/local/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
/usr/local/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/local/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
```

**Comment by b-scholz** [comment]
Can you add the Souffle copyright headers and rename the header files to have the suffix `.h` (instead of `.hpp`)?

**Comment by HerbertJordan** [comment]
Hi quentin,

thanks for the detailed reply. I agree, in an OpenMP setup, those logs are contention-free except for the growing case. Thus, the overhead is neglectable, and your benchmarks demonstrate this. 

An example shard-based implementation following the outlined proposal can be found [here](https://github.com/facebook/folly/blob/master/folly/concurrency/ConcurrentHashMap.h). It uses 256 shards by default. Each shard grows independently. So inserts and reads from other shards are not blocked. And if I understand correctly, even reads are not blocked for the shard on which a resize is performed. The rehashed table is computed and swapped in atomically. (Reads are wait-free). 

The full implementation is Apache 2.0, so maybe we could consider reusing their implementation. @b-scholz would this be a compatible license?

**Comment by b-scholz** [comment]
Apache license is compatible, and thanks for this great reference. First, however, we should do some benchmarking to see whether folly/ConcurrentHashMap has approximately the same performance as Quentin's approach. 

In general, I would prefer a hand-tailored data structure for Souffle, which we can adapt over time for its use case.

**Review by b-scholz — APPROVED** [review]

**Comment by b-scholz** [comment]
Thanks for the contribution. 

It would be great to experiment with folly/ConcurrentHashMap in the context of Souffle as a future project.

**Pull request merged**
