### PR TITLE
DRAFT: Memory Pool for BTrees

### PR DESCRIPTION
**Pull request by b-scholz**
This is a memory pool implementation to overcome the speed-issues / memory issue of adding virtual to the destructor. This is a sketch - please don't merge.

For parallel execution, it is not fast enough. We require a high-performance implementation that 
(1) makes methods allocate()/free() race-free; currently it only works for sequential execution
(2) uses thread-local memory for memory chunks to minimize synchronization
(3) experiments with memory_chunk size / currently set to a multiple of key size / perhaps fix sized etc.

With the program

#define N 3000
.decl A,B(x:number, y:number)

A(1,2).
A(N, 1).
A(x+1,x+2) :- A(x,_),  x < N.

B(x,y) :- A(x,y).
B(x,z) :- B(x,y), A(y,z).

.printsize B
Runtime reduces from 10.37s to 9.6s.

I feel it is worthwhile to pursue this.

### CODE REVIEW

**Comment by b-scholz** [comment]
This is an updated version; there are still some memory issues related to thread-local arenas. 

Please don't merge.

**Comment by ohamel-softwaresecure** [comment]
Available on https://github.com/ohamel-softwaresecure/souffle/tree/fix-btree-mempool.
@b-scholz asked if I could pickup and finish #1419. So here it is.

Given program:
```
#define N 3000
.decl A,B(x:number, y:number)

A(1,2).
A(N, 1).
A(x+1,x+2) :- A(x,_), x < N.

B(x,y) :- A(x,y).
B(x,z) :- B(x,y), A(y,z).
.printsize B
```

Horrifically biased, uncontrolled, single sample BS micro benchmark results (GCC, -O3):

** ( Commit: 947727917 ) Before:**
```
⋊> ~/p/souffle on master ◦ time ./src/souffle -D- TOY/ank.dl                                                                                                19:40:46
B       9003000
6.59user 0.07system 0:06.67elapsed 99%CPU (0avgtext+0avgdata 103680maxresident)k
0inputs+0outputs (0major+24411minor)pagefaults 0swaps
⋊> ~/p/souffle on master ◦ time ./src/souffle -D- TOY/ank.dl -j8                                                                                            19:40:54
B       9003000
35.59user 0.05system 0:04.58elapsed 777%CPU (0avgtext+0avgdata 103672maxresident)k
0inputs+0outputs (0major+24671minor)pagefaults 0swaps
```

**After:**
```
⋊> ~/p/souffle on fix-btree-mempool  time ./src/souffle -D- TOY/ank.dl                                                                                      19:32:54
B       9003000
6.44user 0.03system 0:06.47elapsed 100%CPU (0avgtext+0avgdata 99004maxresident)k
0inputs+0outputs (0major+23278minor)pagefaults 0swaps
⋊> ~/p/souffle on fix-btree-mempool  time ./src/souffle -D- TOY/ank.dl -j8                                                                                  19:34:05
B       9003000
41.56user 0.26system 0:05.37elapsed 778%CPU (0avgtext+0avgdata 101748maxresident)k
0inputs+0outputs (0major+97903minor)pagefaults 0swaps
```

So far doesn't look good. Maybe you do get some wins based mem usage, but the `-j8` case just flops with the pool.

**Comment by b-scholz** [comment]
I will run a bigger benchmark (Amazon's VPC) and check whether there are advantages. 
Alternatively, we revert back to the non-virtual destructor solution with appropriate casting so that we don't get memory issues.

**Comment by b-scholz** [comment]
Oh dear - I opened a new pull-request that differentiates between inner and leaf node. 
With the cases, we can statically cast the appropriate type and perform the right delete operation. 

Can you check with your checkers whether this still causes issues?

**Comment by ohamel-softwaresecure** [comment]
Sure. For future reference, you too can do this at home with `./bootstrap; and ./configure --enable-debug --enable-sanitise-memory`. Perhaps we should change the CI to run the suite in debug/san mode as well as release.

**Comment by b-scholz** [comment]
Another alternative is to make the memory_pool lock-free and remove the thread_mempool. 

We could use code examples such as the following:
https://gist.github.com/glampert/c40f2584d2fbc72316e1c8a6ef1c0436/revisions
http://moodycamel.com/blog/2014/solving-the-aba-problem-for-lock-free-free-lists

Unfortunately, we need to consider the index and the current pointer simultaneously.

**Comment by ohamel-softwaresecure** [comment]
I think we need to spend some time profiling precisely where it goes wrong. It shouldn't be significantly slower than a good general purpose allocator.

**Comment by b-scholz** [comment]
Indeed...

**Comment by ohamel-softwaresecure** [comment]
Ooof, that's overkill. Here's the implementation I went with for `threadlocal_pool`. There are no locks. OTTOMH possible issues: triple-indirection (`thread_pools` -> `chunks` -> `chunk`), possible cache-line conflict (storage for `thread_pools`, unlikely, since they're mostly read-only).
All at least one indirection can be avoided with a cache ptr in `memory_pool`.

```
template <class T, int N>
class threadlocal_pool {
    std::vector<memory_pool<T, N>> thread_pools{size_t(omp_get_max_threads())};

public:
    threadlocal_pool() = default;
    threadlocal_pool(threadlocal_pool&&) = default;
    threadlocal_pool& operator=(threadlocal_pool&&) = default;

    auto allocate() {
        return thread_pools[omp_get_thread_num()].allocate();
    }
};
```

**Comment by mmcgr** [comment]
The Memory test on Jenkins ran the tests with the sanitiser enabled, but previously specifically disabled the test that was failing here. I've enabled it now, so future changes to the BTree will have to delete the right types.

The current test script for that is:
```sh
./bootstrap
./configure --enable-debug --enable-sanitise-memory
make -j4
TESTSUITEFLAGS=-j4 SOUFFLE_CATEGORY=Syntactic,Semantic,FastEvaluation,Profile,Interface make check -j4
```

**Comment by b-scholz** [comment]
I experimented a little bit further without threaded memory pools. I thought the current version could be improved by avoiding a recursive deletion via the inner_nodes; however, I had no luck getting a performance improvement. See the code below:
```
 void clear() {
        std::stack<std::size_t> rstack;
        rstack.push(0);
        node* current = root;
        while (current != nullptr) {
            if (current->isLeaf()) {
                leaf_node* leaf = static_cast<leaf_node*>(current);
                rstack.pop();
                current = current->parent;
                delete leaf;
            } else {
                inner_node* inner = static_cast<inner_node*>(current);
                std::size_t idx = rstack.top();
                rstack.pop();
                if (idx < inner->numElements) {
                    current = inner->children[idx];
                    rstack.push(idx + 1);
                    rstack.push(0);
                } else {
                    current = current->parent;
                    delete inner;
                }
            }
        }
        root = nullptr;
        leftmost = nullptr;
    }
```
Note that I removed the destructor of inner_node and I used a vector on purpose (instead of a stack) because it may give better performance by reversing sufficient number of elements. 
This version is 0.1 sec slower or equally fast. Hence, no substantial improvement. 
I guess a memory pool might be more advantageous to reduce the number of memory allocations/deletions.

**Comment by b-scholz** [comment]
Perhaps we retire this PR. If we have something faster, we can revive this work at a later stage. 
With a recent PR, we could rewrite the destructors to static ones. That should be fine for the time being.

**Pull request closed without merging**
